### ISSUE TITLE
[Windows 8][Modern] Game is not gracefully disposing

### ISSUE THREAD

**Issue by Haplois** [MonoGame/MonoGame#1492]
When I dispose the game object it is still trying to update...

System.ObjectDisposedException
   at Microsoft.Xna.Framework.Game.AssertNotDisposed()
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.MetroGameWindow.Tick()
   at Microsoft.Xna.Framework.MetroGamePlatform.<StartRunLoop>b__0(Object o, Object a)

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
