### ISSUE TITLE
MonoGameContentProcessors DxtCompressed iOS bug

### ISSUE THREAD

**Issue by Christian24** [MonoGame/MonoGame#2580]
Hi,

I am using MonoGameContentProcessors for building my game content for iOS. This used to work fine, but now I use  DxTCompressed as texture format. Now it does not seem to build one file. I have uploaded it here, so you can take a look (https://onedrive.live.com/redir?resid=C0CE760A348CC8BF!7446&authkey=!ANpmIJWBflfL4js&ithint=file%2c.dds). This file builds fine with XNA for Windows (& Phone). This is the error Visual Studio throws when attempting to build it:

Error   3   Building content threw NotSupportedException: Specified method is not supported.
   at MonoGameContentProcessors.Processors.MGTextureProcessor.Process(TextureContent input, ContentProcessorContext context) in E:\MonoGame\MonoGame\MonoGame.ContentPipeline\ContentProcessors\Processors\MGTextureProcessor.cs:line 98
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.BuildCoordinator.BuildAssetWorker(BuildItem item)
   at Microsoft.Xna.Framework.Content.Pipeline.BuildCoordinator.BuildAsset(BuildItem item)
   at Microsoft.Xna.Framework.Content.Pipeline.BuildCoordinator.RunTheBuild()
   at Microsoft.Xna.Framework.Content.Pipeline.Tasks.BuildContent.RemoteProxy.RunTheBuild(BuildCoordinatorSettings settings, TimestampCache timestampCache, ITaskItem[] sourceAssets, String[]& outputContent, String[]& rebuiltContent, String[]& intermediates, Dictionary`2& dependencyTimestamps, KeyValuePair`2[]& warnings)   E:\Felicity\Wheelom Content\Textures\Old Tiles\Cracked.dds  ContentBuilder

Thanks for the great efforts that you guys make,
Christian

**Comment by Jjagg** [comment]
The linked file builds fine in develop :)
