### ISSUE TITLE
Game.OnExiting is called too late when closing with close window button

### ISSUE THREAD

**Issue by wldevries** [MonoGame/MonoGame#3210]
The problem is that the Game does not call OnExiting for a while after clicking the close button of the window with the mouse. We use the OnExiting method to keep track of the state of the game, but it is not useful for this purpose because it has a delay. Not being able to know whether game is exiting causes crashes because we get the mouse state every update. 

This is consistently reproduceable with MonoGame 3.2 OpenGL on a Windows 8.1 Pro 64bit desktop.

A nice way to handle this would be to suspend closing the window until things have cleaned up. Unfortunately GameWindow does not provide functionality to cancel closing of the window.

```
System.InvalidOperationException: Could not convert point {X=1566,Y=162} from screen to client coordinates. Windows error: 1400
   at OpenTK.Platform.Windows.WinGLNative.PointToClient(Point point)
   at OpenTK.NativeWindow.PointToClient(Point point)
   at Microsoft.Xna.Framework.Input.Mouse.GetState(GameWindow window)
   at Microsoft.Xna.Framework.Input.Mouse.GetState()
   at SilverFit.Boom.Input.MouseComponent.Update(GameTime gameTime) in c:\Users\wouter\Documents\Git\Boom\BoomApplication\Input\MouseComponent.cs:line 231
   at Microsoft.Xna.Framework.Game.<.cctor>b__19(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at SilverFit.Boom.ApplicationHolder.Update(GameTime gameTime) in c:\Users\wouter\Documents\Git\Boom\BoomApplication\ApplicationHolder.cs:line 261
   at SilverFit.Common.SilverApplicationHolder.Update(GameTime gameTime) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\Common\Common\SilverApplicationHolder.cs:line 24
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.OpenTKGameWindow.OnUpdateFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.OnUpdateFrame(FrameEventArgs e)
   at OpenTK.GameWindow.OnUpdateFrameInternal(FrameEventArgs e)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch update_watch, Double& next_update, FrameEventArgs update_args)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run(Double updateRate)
   at Microsoft.Xna.Framework.OpenTKGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at SilverFit.Common.BootStrap.RunGame(SilverSettings silversettings, ISilverFitGameSettings gameSettings, Func`2 gameFactory) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\Common\Common\BootStrap.cs:line 29
   at SilverFit.CognitionGames.Program.StartGame(SilverSettings silversettings, GameStartInformation startinfo, CognitionSettings setting) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\CognitionGames\CognitionGames\Program.cs:line 46
   at SilverFit.CommonWpf.GameBootstrap.DebugStartViewModel.Start[T](StartGame`1 startDelegate) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\CommonWpf\GameBootstrap\DebugStartViewModel.cs:line 317
   at SilverFit.CognitionGames.Program.GameMain(String[] args) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\CognitionGames\CognitionGames\Program.cs:line 42
   at SilverFit.Common.ErrorHandler.ReleaseMain(Main main, String[] args) in c:\Users\wouter\Documents\Visual Studio 2013\Projects\Alois\trunk\Common\Common\ErrorHandler.cs:line 51
```

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
