### ISSUE TITLE
Android packaging fails when referencing MonoGame.Framework.Net assembly

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#3480]
1. Download and install the latest developer build.
2. Reference both MonoGame.Framework.dll and MonoGame.Framework.Net.dll from C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Android
3. The packaging stage of the build fails with the following error:

The "BuildApk" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Ionic.Zip.ZipFile._InternalAddEntry(ZipEntry ze)
   at Ionic.Zip.ZipFile.AddFile(String fileName, String directoryPathInArchive)
   at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String supportedAbis, String apkInputPath, String apkOutputPath)
   at Xamarin.Android.Tasks.BuildApk.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
Build FAILED.

**Comment by dtaylorus** [comment]
Note that the version of MonoGame.Framework.Net.dll from the Cocos2D-Xna fork works.

Apparently this is because they are using separate AssemblyInfo.cs files with different assembly Guids for the MonoGame.Framework and MonoGame.Framework.Net.dll.

**Comment by vostok4** [comment]
Just ran into this myself. @dtaylorus did you come up with any workaround in the meantime?

**Comment by Nezz** [comment]
Here is the original issue:
https://github.com/mono/MonoGame/issues/2981

You can fix it in one minute by changing the intermediate output directores (obj dir) in both projects, so they won't conflict.

**Comment by dtaylorus** [comment]
I was able to work around the problem first by using the nuget binaries from the Cocos2D project (where they've fixed this problem correctly by changing the Guid for MonoGame.Framework.Net.dll), and later I decided to just directly include the source code for the small feature I needed (text input) from that dll so I could use a more recent MonoGame.Framework.dll binary.

These obj dir workarounds don't work for me. I don't build the MonoGame dll's from sources--I use the binaries from the alpha nuget package.

**Comment by Nezz** [comment]
I think they have to be in different directories then. Can you verify?

**Comment by dtaylorus** [comment]
When I add the NuGet package from Visual Studio, I don't see an option to choose a directory.

I haven't tried moving the assemblies around on the disk for the installed version of MonoGame, if that's what you mean.

There's so little I need from the assembly that I'm happy just using the source I need rather than the built dll.

This bug might make it difficult for others to use MonoGame, though.
________________________________

**Comment by Nezz** [comment]
Yes, it is annoying. I guess you use it because of messagebox or keyboardinput. Good news is that I have recently added a modern version of those that is included in the main library. Hopefully it will be soon available via NuGet.

**Comment by dtaylorus** [comment]
Awesome. Yes, I use the Guide for text input (player name and optional email) and that's all I need.

Great to hear that will be in the main library!
________________________________

**Comment by Eversor** [comment]
Same error here when building from source, very repeatable: simply try to package a new app that references both Monogame and Monogame.net
