### ISSUE TITLE
XAudio2 Cue.Play() fail

### ISSUE THREAD

**Issue by GrafSeismo** [MonoGame/MonoGame#4446]
```
Cue.Apply3D(Listener, Emitter);
Cue.Play(); // <--- Error happen here
```

An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll but was not handled in user code

Additional information: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown

SharpDX.SharpDXException was unhandled by user code
  HResult=-2003435519
  Message=HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
  Source=SharpDX
  StackTrace:
       at SharpDX.Result.CheckError()
       at SharpDX.XAudio2.XAudio2.CreateSourceVoice_(SourceVoice sourceVoiceOut, IntPtr sourceFormatRef, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callbackRef, Nullable`1 sendListRef, Nullable`1 effectChainRef)
       at SharpDX.XAudio2.SourceVoice.CreateSourceVoice(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callback, EffectDescriptor[] effectDescriptors)
       at SharpDX.XAudio2.SourceVoice..ctor(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, Boolean enableCallbackEvents, EffectDescriptor[] effectDescriptors)
       at SharpDX.XAudio2.SourceVoice..ctor(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, Boolean enableCallbackEvents)
       at SharpDX.XAudio2.SourceVoice..ctor(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio)
       at Microsoft.Xna.Framework.Audio.SoundEffect.PlatformSetupInstance(SoundEffectInstance inst)
       at Microsoft.Xna.Framework.Audio.SoundEffect.GetPooledInstance(Boolean forXAct)
       at Microsoft.Xna.Framework.Audio.SoundBank.GetSoundEffectInstance(Int32 waveBankIndex, Int32 trackIndex)
       at Microsoft.Xna.Framework.Audio.PlayWaveEvent.Play(Boolean pickNewWav)
       at Microsoft.Xna.Framework.Audio.PlayWaveEvent.Play()
       at Microsoft.Xna.Framework.Audio.XactClip.Update(Single dt)
       at Microsoft.Xna.Framework.Audio.XactClip.Play()
       at Microsoft.Xna.Framework.Audio.XactSound.Play()
       at Microsoft.Xna.Framework.Audio.Cue.Play()
       at MyProject.Engine.Audio.Audio3D.Play()
       at MyProject.Engine.Audio.Audio3D.Play(String newCueName)
       at MyProject.Menu.MainMenuScreen.LoadContent()
       at MyProject.Engine.Manager.ScreenManager.AddScreen(Screen screen)
       at MyProject.Engine.GameScreen.LoadingScreen.Update(GameTime gameTime, Boolean otherScreenHasFocus, Boolean coveredByOtherScreen)
       at MyProject.Engine.Manager.ScreenManager.Update(GameTime gameTime)
       at MyProject.Engine.MyEngine.Update(GameTime gameTime)
       at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.UAPGameWindow.Tick()
       at Microsoft.Xna.Framework.UAPGamePlatform.<>c.<StartRunLoop>b__12_0(Object o, Object a)
  InnerException:

May the following link may help: https://social.msdn.microsoft.com/Forums/en-US/84639f89-95f8-4e51-adb0-5ebdea3c95e2/xaudio2einvalidcall-hresult-0x88960001?forum=wingameswithdirectx

**Comment by nkast** [comment]
I am getting the same error with the latest develop build.
The way to reproduce is 
-create a new WUP and add those lines in `LoadContent()`
```
            var testSound = this.Content.Load<SoundEffect>("test");
            var warmInstance = testSound.CreateInstance(); // <-- SharpDXException
```
-add a wav file (test.wav) and build with Medium or low quality.

error: SharpDXException
HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
stack:
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.XAudio2.CreateSourceVoice_(SourceVoice sourceVoiceOut, IntPtr sourceFormatRef, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callbackRef, Nullable`1 sendListRef, Nullable`1 effectChainRef)
   at SharpDX.XAudio2.SourceVoice.CreateSourceVoice(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callback, EffectDescriptor[] effectDescriptors)
   at Microsoft.Xna.Framework.Audio.SoundEffect.PlatformSetupInstance(SoundEffectInstance inst)
   at Microsoft.Xna.Framework.Audio.SoundEffect.CreateInstance()
   at TestAudio1_Universal.Game1.LoadContent()

Building the sound with high quality is fine. 
The bug occurs only for windows store apps. Desktop/DX apps run fine.

**Comment by tomspilman** [comment]
I'm investigating this a bit to see what is going on.

**Comment by nkast** [comment]
Here's where the pipeline calculates `blockAlign`
https://github.com/MonoGame/MonoGame/blob/4a787f5c1ba2874392ed18ac2f00679158b03d75/MonoGame.Framework.Content.Pipeline/Audio/DefaultAudioProfile.cs#L203-L204
That's correct for PCM but doesn't work for ADPCM. `bitsPerSample` is always 4, `(bitsPerSample * channelCount) / 8;` gives 0 or 1.

When we load the SoundEffect and create `WaveFormatAdpcm()`, sharpddx will cast blockAlign back to (int16). Therefore bug #5150 is irrelevant. https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/Multimedia/WaveFormatAdpcm.cs#L50

When blockAlign is 1 (2 channels), we get incorrect values here that later cause a DevideByZeroException.
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/Multimedia/WaveFormatAdpcm.cs#L68-L69
SamplesPerBlock = (ushort)(1 * 2 / 2 - 12) = (ushort)-12 = 65524
averageBytesPerSecond = (SampleRate * 1) / 65524 = SampleRate / 65524 = 0 // because SampleRate< 65524 and averageBytesPerSecond is an integer.

When blockAlign is 0 (1 channels), sharpDX fallback to some arbitrary values (256,512,1024).
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/Multimedia/WaveFormatAdpcm.cs#L52-L66
But this doesn't work either because it sets the local `blockAlign` while the member `this.blockAlign` remains zero! :boom: We still get an exception from XAudio.

I tested all 3 values (256,512,1024) here, for example `new WaveFormatAdpcm(sampleRate, channels, 512);`  and always work. No exception. 
https://github.com/MonoGame/MonoGame/blob/13209fb0fcf7adeabd6a1317ffd695143764a7d2/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L190

Although we must fix this on the pipeline. I suspect that soundEffect XNBs won't be usable on XNA either.

**Comment by nkast** [comment]
ffprobe doesn't return BlockAlign info. 
There was a method `private static byte[] GetRawWavData(BinaryReader reader, ref int blockAlign)` to extract the value from the generated riff header. 
It was removed by #5001 and it wasn't used at the time.
https://github.com/MonoGame/MonoGame/pull/5001/files

**Comment by nkast** [comment]
@tomspilman Can we schedule this bug for 3.6 Release?
