### ISSUE TITLE
Size of destination not validated when using Texture  SetData / GetData 

### ISSUE THREAD

**Issue by james0x0A** [MonoGame/MonoGame#5260]
MonoGame does not validate the size of data passed through Texture.GetData and Texture.SetData.   Under XNA The data must match the size of the destination, in bytes, exactly else return an ArgumentException.  

.Net handles this case silently with DesktopGL,  but Mono currently crashes with an uninformative native error when it encounters this situation. 

XNA Throws:
GetData:
```
Unhandled Exception: System.ArgumentException: The size of the data passed in is too large or too small for this resource.
   at Microsoft.Xna.Framework.Graphics.Texture.ValidateTotalSize(_D3DSURFACE_DESC* __unnamed000, UInt32 dwLockWidth, UInt32 dwLockHeight, UInt32 dwFormatSize, UInt32 dwElementSize, UInt32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data)
   at WindowsGame4.Game1.LoadContent() in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Game1.cs:line 62
   at Microsoft.Xna.Framework.Game.Initialize()
   at WindowsGame4.Game1.Initialize() in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Game1.cs:line 38
   at Microsoft.Xna.FramewoThe program '[0x38AC] WindowsGame4.exe' has exited with code 0 (0x0).
rk.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at WindowsGame4.Program.Main(String[] args) in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Program.cs:line 15
```

SetData:
```
Unhandled Exception: System.ArgumentException: The size of the data passed in is too large or too small for this resource.
   at Microsoft.Xna.Framework.Graphics.Texture.ValidateTotalSize(_D3DSURFACE_DESC* __unnamed000, UInt32 dwLockWidth, UInt32 dwLockHeight, UInt32 dwFormatSize, UInt32 dwElementSize, UInt32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data)
   at WindowsGame4.Game1.LoadContent() in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Game1.cs:line 58
   at Microsoft.Xna.Framework.Game.Initialize()
   at WindowsGame4.Game1.Initialize() in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Game1.cs:line 38
   at Microsoft.Xna.FramewoThe program '[0xD54] WindowsGame4.exe' has exited with code 0 (0x0).
rk.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at WindowsGame4.Program.Main(String[] args) in c:\devel\projects\WindowsGame4\WindowsGame4\WindowsGame4\Program.cs:line 15

```

**Comment by Jjagg** [comment]
Can you give a test case for when you get the native exception? IIRC XNA throws the exception you get when elementCount does not match the size of the data you get. Though maybe it throws exactly the same thing when the physical size is wrong.

Can you check if #5121 fixes this? I really should finish that up...

**Comment by james0x0A** [comment]
```

            var texture = new Texture2D(graphics.GraphicsDevice, 4, 4, false, SurfaceFormat.Color);
            uint[] data = new uint[16];


            Console.WriteLine("IN:");
            for (ushort i = 0; i < data.Length; i++)
            {
                data[i] = i;
                Console.Write("{0} ", i );
            }

            texture.SetData(data);

            ushort[] shortData = new ushort[16];

            
            texture.GetData(shortData);  // XNA Throws.    MonoGame on Mono hard crashes.

            Console.WriteLine("");
            Console.WriteLine("OUT:");
            foreach (ushort datum in shortData)
            {
                Console.Write("{0} ", datum);
            }
```

**Comment by james0x0A** [comment]
Looks like #5121 resolves this in every case I tested.

**Comment by james0x0A** [comment]
closing this in preference to #1455 and #5119

**Comment by Jjagg** [comment]
Thanks for testing @james0x0A !
