### ISSUE TITLE
Output window is spammed by debugger null reference exceptions from Mono/Xamarin

### ISSUE THREAD

**Issue by nebosite** [MonoGame/MonoGame#5602]
When I debug my app on android, I get dozens of these exceptions every second:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.Debugger.ProjectVisualStudio.GetCSharpProjectContent(VSProject vsproject) in C:\data\lanes\3513\00fa5cc4\source\xamarinvs\src\Core\VisualStudio\Debugging\ProjectVisualStudio.cs:line 100
   at Xamarin.VisualStudio.Debugger.ProjectVisualStudio..ctor(VSProject vsproject) in C:\data\lanes\3513\00fa5cc4\source\xamarinvs\src\Core\VisualStudio\Debugging\ProjectVisualStudio.cs:line 114
   at Xamarin.VisualStudio.Debugger.ExpressionResolver.FindOrCreateDocument(String source) in C:\data\lanes\3513\00fa5cc4\source\xamarinvs\src\Core\VisualStudio\Debugging\ExpressionResolver.cs:line 31
   at Xamarin.VisualStudio.Debugger.ExpressionResolver.ResolveType(String identifier, SourceLocation location) in C:\data\lanes\3513\00fa5cc4\source\xamarinvs\src\Core\VisualStudio\Debugging\ExpressionResolver.cs:line 45
   at Xamarin.VisualStudio.Debugger.MonoToolsDebuggerSession.OnResolveType(String identifier, SourceLocation location) in C:\data\lanes\3513\00fa5cc4\source\xamarinvs\src\Core\VisualStudio\Debugging\MonoToolsDebuggerSession.cs:line 78
   at Mono.Debugging.Client.DebuggerSession.ResolveIdentifierAsType(String identifier, SourceLocation location)
   at Mono.Debugging.Evaluation.NRefactoryExpressionResolverVisitor.ReplaceType(String name, Int32 genericArgs, Int32 offset, Int32 length, Boolean memberType)
   at Mono.Debugging.Evaluation.NRefactoryExpressionResolverVisitor.VisitIdentifierExpression(IdentifierExpression identifierExpression)
   at ICSharpCode.NRefactory.CSharp.IdentifierExpression.AcceptVisitor(IAstVisitor visitor)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor.VisitBinaryOperatorExpression(BinaryOperatorExpression binaryOperatorExpression)
   at ICSharpCode.NRefactory.CSharp.BinaryOperatorExpression.AcceptVisitor(IAstVisitor visitor)
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Resolve(DebuggerSession session, SourceLocation location, String expression, Boolean tryTypeOf)
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Resolve(DebuggerSession session, SourceLocation location, String exp)
   at Mono.Debugging.Soft.SoftDebuggerSession.EvaluateExpression(ThreadMirror thread, String expression, BreakEvent bp)

**Comment by Jjagg** [comment]
This is most likely a Xamarin bug.
