### ISSUE TITLE
Stretching Window too far causes exception

### ISSUE THREAD

**Issue by Oyyou** [MonoGame/MonoGame#5667]
I have my "Window.AllowUserResizing" set to 'true'.

To test the limits, I stretched the Window across both monitors. That is what caused the exception to be thrown.
"SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect."

I have created my event for "ClientSizeChanged", but obviously that makes no difference as this is happening in SharpDX

`

    private void Window_ClientSizeChanged(object sender, EventArgs e)
    {
      if (graphics.PreferredBackBufferHeight < 480)
      {
        graphics.PreferredBackBufferHeight = 480;
        graphics.ApplyChanges();
      }

      if (graphics.PreferredBackBufferHeight > 1440)
      {
        graphics.PreferredBackBufferHeight = 1440;
        graphics.ApplyChanges();
      }

      if (graphics.PreferredBackBufferWidth < 800)
      {
        graphics.PreferredBackBufferWidth = 800;
        graphics.ApplyChanges();
      }

      if (graphics.PreferredBackBufferWidth > 2560)
      {
        graphics.PreferredBackBufferWidth = 2560;
        graphics.ApplyChanges();
      }

      ScreenHeight = graphics.PreferredBackBufferHeight;
      ScreenWidth = graphics.PreferredBackBufferWidth;
    }

`

Thanks

**Comment by nkast** [comment]
Can you post a screenshot of DXDiag.exe (/Display)?  or just what Feature levels your card support?

Have you tried with HiDef profile or with the OpenGL project?

**Comment by Oyyou** [comment]
My DxDiag info is [here](https://jpst.it/Y6fl).

I've just created an OpenGL project and it works perfectly fine, which means it's only DirectX.

I tried setting on HiDef, but I get a 'NullReferenceException' in my "spriteBatch.End()" after it's changed.

**Comment by nkast** [comment]
All right, it doesn't look like a limitation of the GPU, it has to be something else. Unfortunately I don' t have dual monitor. I might be helpful to have  the full stack trace of the exception and at what size the exception is thrown. Is it something like after >2048px, >4096 or it's completely random?

**Comment by Oyyou** [comment]
I just chucked this in the "Update" method to see where it's happening
`
      graphics.PreferredBackBufferWidth++;
      graphics.ApplyChanges();
`
and you're right. It's when the window is getting > 4096px.

Stack trace below

SharpDX.SharpDXException occurred
  HResult=0x80070057
  Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

  Source=SharpDX
  StackTrace:
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.ResizeBuffers(Int32 bufferCount, Int32 width, Int32 height, Format newFormat, SwapChainFlags swapChainFlags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges()
   at PleaseThem.Game1.Update(GameTime gameTime) in E:\Projects\CGJ12016\PleaseThem\Game1.cs:line 127
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at PleaseThem.Program.Main() in E:\Projects\CGJ12016\PleaseThem\Program.cs:line 18

**Comment by nkast** [comment]
Now we have to make HiDef work to see if it's a limit of the selected feature level or a hard limit of the driver/card.
Can you temporary disable spritebatch drawing and test HiDef? Also if you can post the stacktrace of NullReferenceException in spritebatch. So far ther are no similar reports.

**Comment by Oyyou** [comment]
When set to HiDef we managed to get a width of 16400px before throwing an exception.

As for the spriteBatch stack trace:
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Setup()
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at PleaseThem.States.MenuState.Draw(GameTime gameTime, SpriteBatch spriteBatch) in E:\Projects\CGJ12016\PleaseThem\States\MenuState.cs:line 59
   at PleaseThem.Game1.Draw(GameTime gameTime) in E:\Projects\CGJ12016\PleaseThem\Game1.cs:line 176
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at PleaseThem.Program.Main() in E:\Projects\CGJ12016\PleaseThem\Program.cs:line 18

From what I can see "GraphicsDevice" inside "SpriteBatch" is 'null', even when I re-initialize the "SpriteBatch" on my PreparingDeviceSettings call.

**Comment by nkast** [comment]
> When set to HiDef we managed to get a width of 16400px before throwing an exception.
Wow that's a hell of a virtual monitor! The limit is 16384, right?

> From what I can see "GraphicsDevice" inside "SpriteBatch" is 'null', even when I re-initialize the "SpriteBatch" on my PreparingDeviceSettings call.

I am not sure what that means but it doesn't sound right. You should  initialize spritebatch just once in Intialize() or in LooadContent().

**Comment by nkast** [comment]
I tried to change the backbuffer under XNA, and found that I can set the Backbuffer up to 16384, even with  Reach Profile. Anything >16384 will throw NoSuitableGaraphicsDevice and reset/destroy the GraphicsDevice.
The test was performed by setting PreferredBackBufferWidth and ApplyChanges, I don't know how XNA will behave with resizing the Client beyond 16384px.

**Comment by chuk95** [comment]
any updates? i currentley have kind of the same issue. when using the hidef profile as soon as i resize my window the GraphicDevice in every spritebatch and rendertarget2d are null. and it throws out null reference exceptions.

**Comment by Jjagg** [comment]
@chuk95 That's a completely different problem. Can you open a new issue for it?

**Comment by chuk95** [comment]
@Jjagg yes i will create a new ticket for this, after some more testing so i can pinpoint the issue

**Comment by willmotil** [comment]
In xna you could set the back buffer to anything you want but make no mistake you cannot get just anything you want thats why your setting the preffered back buffer not the back buffer itself.

In monogame just the same as xna if you set the preffered back buffer to a specific screen resolution that you know exists on your card (and the refresh rate and color format also exists) then call apply changes in fullscreen you can change your actual display mode to that resolution. 

My guess is some how doing this in this case... the backbuffer is actually trying to set a invalid screen resolution.

If the graphics device attempted to set the backbuffer to a non existent screen resolution. Then that is simply not possible because the monitors hardware scaler cant support something that doesn't exist. 
So some were along the line you would get a error if not from the os. Then one from the card.

Either way the graphics device would be in a bad state or probably null. SpriteBatch relys on the device so that would just be passed on to it.
