### ISSUE TITLE
SamplerState.AnisotropicClamp throws 'SharpDX.SharpDXException 

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#5674]
Setting SamplerState to AnisotropicClamp throws exception: 

```
SharpDX.SharpDXException was unhandled
  HResult=-2147024809
  Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

  Source=SharpDX
  StackTrace:
       at SharpDX.Result.CheckError()
       at SharpDX.Direct3D11.Device.CreateSamplerState(SamplerStateDescription& samplerDescRef, SamplerState samplerStateOut)
       at SharpDX.Direct3D11.SamplerState..ctor(Device device, SamplerStateDescription description)
       at Microsoft.Xna.Framework.Graphics.SamplerState.GetState(GraphicsDevice device) in p:\MonoGame\MonoGame.Framework\Graphics\States\SamplerState.DirectX.cs:line 53
       at Microsoft.Xna.Framework.Graphics.SamplerStateCollection.PlatformSetSamplers(GraphicsDevice device) in p:\MonoGame\MonoGame.Framework\Graphics\SamplerStateCollection.DirectX.cs:line 54
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders) in p:\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1298
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(Boolean applyShaders) in p:\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 477
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, VertexDeclaration vertexDeclaration, Int32 vertexCount) in p:\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1408
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration) in p:\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 1045
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 primitiveCount) in p:\MonoGame\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 1006
```
      
Platform: Windows/DirectX
Profile: Reach
Version: latest Git source.

XNA/Reach & MG 3.5.1/Reach works just fine.

**Comment by nkast** [comment]
This one is not easy to reproduce. 
You need either a true DX9.1 card or modify GraphicsDevice to force a level 9.1 device when Profile = Reach .(currently it will create a 9.3 device which basically is HiDef).
