### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in MonoGame.Framework.dll

### ISSUE THREAD

**Issue by ItsEddie** [MonoGame/MonoGame#5787]
Hey Monogame,

I may be missing something very obvious. I'm working on a small little engine to deploy on top of Monogame, and I accidently messed up my code. I've re-downloaded the source code from my Github project, however, upon launch (and fixing some of the normal resource missing issues), it seems to throw a very vague and arbitrary error with no indication to what is causing the issue.

`An unhandled exception of type 'System.NullReferenceException' occurred in MonoGame.Framework.dll`

On 

`public MonoGame()`

MonoGame() is the class that derives from `Game`, in a new project that 'd be `Game1 : Game`. The error **is not** thrown on anything **in** the MonoGame() function.

I've removed and added different versions and platforms of Monogame, even downloaded the Nuget version but to no prevail. 

`System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MonoGame.Framework
  StackTrace:
       at Microsoft.Xna.Framework.MetroGamePlatform..ctor(Game game)
       at Microsoft.Xna.Framework.GamePlatform.PlatformCreate(Game game)
       at Microsoft.Xna.Framework.Game..ctor()
       at Monogame_Engine_Library.MonoGame..ctor() in C:\Users\Gebruiker\Desktop\Monogame-GameMaker-Engine-master\Monogame Engine Library\MonoGame.cs:line 79
       at Monogame_Engine.ExampleGame..ctor()
       at Monogame_Engine.Program.Main() in C:\Users\Gebruiker\Desktop\Monogame-GameMaker-Engine-master\Monogame Engine\Program.cs:line 17
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: `

I'm running on **Windows 10** and have heard some users having similar problems in **Windows 8**.

1. Remove debug/bin folders. **Doesn't work.**
2. Remove and add back Monogame DLL. **Doesn't work.**
3. Change platform target from x86 to Any CPU / Vice Versa. **Doesn't work.**

## Update
After removing the downloaded source, and re-extracting it, I've finally come one step forward and now it throws the error at the 'Content' class, which strangely enough equals to null. 

`

        /// <summary>
        /// Example Game constructor.
        /// </summary>
        public MonoGame()
        {
            GraphicsDeviceManager = new GraphicsDeviceManager(this);
            GraphicsDeviceManager.PreparingDeviceSettings += GraphicsDeviceManager_PreparingDeviceSettings;
            Content.RootDirectory = "Content";
        }

`

`{"Object reference not set to an instance of an object."}`
MonoGame.Framework (Version 3.6.0.1625, Runtime v4.0.30319, Specific Version: No) 

## Issue Resolved
Alright, so once re-extracted, the error was thrown even more specifically after restarting. This time I discovered that it was not loading .xnb but it was loading .fx files. Now whether or not this is a Monogame issue I'm not sure of - in any case the debugger plainly refused to show me the origin of the error, and lead me to believe the Game class itself was broken.

As to how to solve this - I'm not sure, I suppose I was lucky.

**Comment by hach-que** [comment]
You can't access Content in the constructor; access it in LoadContent instead.

**Comment by Jjagg** [comment]
> You can't access Content in the constructor

The `_content` field which is returned by the `Content` property getter is assigned in the `Game` constructor: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L66
So `Content` should not be equal to `null` in the `Game1` constructor. The `Content.RootDirectory = "Content";` statement is in the templates too.

Regarding the OP, it seems more likely that there is something wrong with the VS installation or something. This is probably not a MonoGame issue. Not something we should worry about IMO.

**Comment by PERECil** [comment]
Besides, it seems (to me at least) a bad practice to name the class `MonoGame`. It may have side effects...

**Comment by Jjagg** [comment]
Issue occured in Windows8 platform which was dropped in #5809.
