### ISSUE TITLE
[Android] Crash with Samsung S8 "entire screen" mode

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5964]
This is a feedback from an independent QA team.

It appears that MonoGame doesn't support the "full entire screen" mode present on Samsung Galaxy S8 phones.

Games are crashing as soon as a touch input is registered. Here's a stack trace I got from the QA team.

```
09-26 11:42:55.102  5945  5945 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at Microsoft.Xna.Framework.Input.Touch.TouchPanel.AddEvent (System.Int32 id, Microsoft.Xna.Framework.Input.Touch.TouchLocationState state, Microsoft.Xna.Framework.Vector2 position, System.Boolean isMouse) [0x00000] in <3fb3607028544688a94cdff6dbac64fc>:0 
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at Microsoft.Xna.Framework.Input.Touch.TouchPanel.AddEvent (System.Int32 id, Microsoft.Xna.Framework.Input.Touch.TouchLocationState state, Microsoft.Xna.Framework.Vector2 position) [0x00000] in <3fb3607028544688a94cdff6dbac64fc>:0 
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at Microsoft.Xna.Framework.Input.Touch.AndroidTouchEventManager.OnTouchEvent (Android.Views.MotionEvent e) [0x00074] in <3fb3607028544688a94cdff6dbac64fc>:0 
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at Microsoft.Xna.Framework.MonoGameAndroidGameView.Android.Views.View.IOnTouchListener.OnTouch (Android.Views.View v, Android.Views.MotionEvent e) [0x00000] in <3fb3607028544688a94cdff6dbac64fc>:0 
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at Android.Views.View+IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v, System.IntPtr native_e) [0x00017] in <0a759b3d693640d3855fc15f27718bdd>:0 
09-26 11:42:55.102  5945  5945 E AndroidRuntime:   at (wrapper dynamic-method) System.Object:51bb64d3-9f69-4269-84e6-9f5681e9293c (intptr,intptr,intptr,intptr)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at md5cedead65730cfb9c4b33fbfd5914d87f.MonoGameAndroidGameView.n_onTouch(Native Method)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at md5cedead65730cfb9c4b33fbfd5914d87f.MonoGameAndroidGameView.onTouch(MonoGameAndroidGameView.java:77)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:10775)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.SurfaceView.dispatchTouchEvent(SurfaceView.java:333)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:607)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:11008)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:136)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
09-26 11:42:55.102  5945  5945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

We don't have a Galaxy S8 in house to give this a spin.

Disabling "full entire screen" mode on the phone works (but games have black borders).

**Comment by dellis1972** [comment]
@mrhelmut do you have sample code setting the mode?

**Comment by mrhelmut** [comment]
Unfortunately no, it's a mode specific to the Galaxy S8 interface that Samsung added. When a fullscreen application starts, the phone ask you if you'd like to enter "full entire screen" mode to accommodate its unconventionally wide display.

**Comment by KonajuGames** [comment]
That looks like `TouchPanel.PrimaryWindow` is `null`, which is set in two places:

- `GamePlatform.Window` setter called in `AndroidGamePlatform` constructor immediately after constructing the `AndroidGameWindow`, or
- `GamePlatform.Dispose` that sets it to `null`.

Now either the `AndroidGamePlatform` was never constructed, which isn't likely, or it may be re-constructing the `AndroidGamePlatform` due to the choice made by the user to use the "full entire screen".  Can the QA team provide the adb logcat output prior to the exception being thrown?  That may give a hint as to what Samsung is doing behind the scenes.

**Comment by mrhelmut** [comment]
Sure, here's the full logcat: https://pastebin.com/Wz5TBFHM

Process is ```com.thepixelhunt.emma```.

**Comment by KonajuGames** [comment]
Might have to add some more logging in the code to see when specific methods are being called.  Is the `GameWindow` being re-created, therefore requiring `TouchPanel.PrimaryWindow` to be updated?

Do you have `ConfigChanges.ScreenLayout` in `ConfigurationChanges` in your `Activity` attribute?  It looks like it changes the screen layout from 720x1339 to 720x1480.

I think this is the approach they followed to repro this.
http://www.androidauthority.com/force-apps-full-screen-samsung-galaxy-s8-769279/
At the bottom of that article it shows the process for making an app use full-screen on the fly.

Looking at the logcat, it appears to resume the app when that full screen button is pressed (relaunching the activity) at the old size of 720x1339, then immediately relaunches the activity again (at 11:42:47.777) at 720x1339 still, but then does a relayout to 720x1480 (at 11:42:47.815, after going through a relayout to 719x1353 for some reason immediately prior to recreating the surface at 720x1480).
