### ISSUE TITLE
Content Pipeline unable to write type with abstract/interface field/property

### ISSUE THREAD

**Issue by headhunter45** [MonoGame/MonoGame#6063]
I'm using 3.6 and trying to port an old XNA game that uses a lot of custom type writers/readers.

The actual example is a lot more complicated than this.
```
public class LogicalExpression {...}
public TrueLogicalExpression : LogicalExpression {...}
public FalseLogicalExpression : LogicalExpression {...}
public class Episode {
    public LogicalExpression Criteria;
}
```

Assuming our xml is setup properly and each of the concrete implementations of LogicalExpression have writers and readers this works fine in XNA.  MonoGame is trying to get a type writer for the LogicalExpression abstract type which for us redirects to the appropriate concrete implementation's writer, but in the process MonoGame tries to get a reader for the LogicalExpression type which doesn't exist.  I think the problem is in ReflectiveWriter<T> it uses the declared type of the property or field instead of the object's actual type.

**Comment by nkast** [comment]
Do you have ContentTypeWriters that inherit a base  ContentTypeWriter, 
something like the following ? 

```
class TrueLogicalExpressionWriter : LogicalExpressionWriter
{
        protected override void Write(ContentWriter output, object value)
        {
            // ...
        }
}
```

**Comment by nkast** [comment]
> MonoGame is trying to get a type writer for the LogicalExpression abstract type which for us redirects to the appropriate concrete implementation's writer, but in the process MonoGame tries to get a reader for the LogicalExpression type which doesn't exist.

I think you might have a similar problem as I had in #5257.
The pipeline ignores the base `ContentTypeWriter` and `ContentTypeWriter.TargetType`. 
Instead, MG is looking for the generic `ContentTypeWriter<T>` and assumes *`T`* is the `TargetType`. 

https://github.com/MonoGame/MonoGame/blob/156f4f861e5257bec9db4ade01927b7a3f79448f/MonoGame.Framework.Content.Pipeline/Serialization/Compiler/ContentCompiler.cs#L46-L60

Any Writer that inherits from `ContentTypeWriter<T>` or `ContentTypeWriter` don't work.

**Comment by nkast** [comment]
Can you give the basic structure of the base writer and the concrete writers ?

**Comment by headhunter45** [comment]
Thanks, I wasn't expecting a reply so fast.  I setup a minimal example, but it's breaking differently.

I changed about 15 lines of code in MGCB and got my content project to build with it, but while trying to figure out why the minimal example was breaking differently I did something similar to what you suggested.  Mine didn't inherit from the base writer, but the base one forwarded calls to the specific writers and that writer is the one that was causing the problem.

I removed this ContentTypeWriter and now it's working in my game, but I've got another example project that's failing differently.
```
    [ContentTypeWriter]
    public class LogicalExpressionBaseContentWriter: ContentTypeWriter<LogicalExpressionBase>
    {
        protected override void Write(ContentWriter output, LogicalExpressionBase value)
        {
            LogicalExpressionSerializer.WriteILogicalExpressionObject(value, output);
        }

        public override string GetRuntimeReader(TargetPlatform targetPlatform)
        {
            throw new NotImplementedException();
        }
    }
```

For the other project it builds fine, but when I try to load the content I get a NullReferenceException with this stack trace.  I'll try debugging that more later.
```
   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(ContentReader reader)
   at Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at Game1.Game1.LoadContent() in c:\users\tom\Source\Repos\CWDemo\Game1\Game1.cs:line 46
   at Microsoft.Xna.Framework.Game.Initialize()
   at Game1.Game1.Initialize() in c:\users\tom\Source\Repos\CWDemo\Game1\Game1.cs:line 33
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Game1.Program.Main() in c:\users\tom\Source\Repos\CWDemo\Game1\Program.cs:line 18
```

This code did work in XNA and doesn't with MonoGame, but I'm not sure how important "fixing" that is since now I can just remove the XNA kludge.

**Comment by headhunter45** [comment]
Here's the minimal example that's generating that null reference exception in case it helps. https://github.com/headhunter45/MonoGameContentPipelineError
