### ISSUE TITLE
Improve Pipeline Tool Filter View

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#6243]
Some suggestions to improve the filter view of the Pipeline Tool.

Remove drop down arrows on "Cleaning" and "Build" lines that do not contain useful info.  All of these lines:

![image](https://user-images.githubusercontent.com/103522/37252319-48d5bc60-24ed-11e8-8688-b0f23bd4a296.png)

And all of these lines:

![image](https://user-images.githubusercontent.com/103522/37252359-d95a6150-24ed-11e8-8d1f-d40de62b6448.png)

Contain useless info in them and we should not show expansion arrows on them.  All those arrows with useless info hidden under it suggest to the user that all the info is useless.  Instead if we only show the arrow when there is useful info... like error messages or warnings... then the arrow becomes a feature and not "visual noise".

The logic could be as simple as if the content didn't generate an error and there is only one captured line of output for the item... then don't render the arrow or allow expansion.

Second it seems we're losing some info in the filter view:

![image](https://user-images.githubusercontent.com/103522/37252394-5bc972fc-24ee-11e8-9994-fb029686ba0d.png)

![image](https://user-images.githubusercontent.com/103522/37252406-85d990c2-24ee-11e8-9af2-5eec041867f8.png)

Here the warning message was lost in the filter view and not visible to the user.  We really need to capture these lines and show them else this view becomes irrelevant as it hides useful information.

Finally we also need an "Expand All" "Colapse All" feature for this view.  Could just be added via a new context menu when right clicking on the view.  Could come in useful for other things in the future too.

**Comment by cra0zy** [comment]
I would say this is connected to: https://github.com/MonoGame/MonoGame/issues/5804

We don't need just to get better info from the Pipeline Tool, but also from the MGCB. I really like what @nkast did with https://github.com/MonoGame/MonoGame/pull/5163

**Comment by tomspilman** [comment]
> We don't need just to get better info from the Pipeline Tool, but also from the MGCB

That would be nice... but we cannot assume perfect formatting from MGCB.

We often depend on 3rd-party tools that have their own ways to format errors.  Us trying to "fix" the error/warning output of all shader compilers, texture compressors, etc to fit our own rules is just going to cause more errors.

I think we have to embrace the fact all we can control a few lines that MGCB outputs:

 1. The "Clean" line.
 2. The "Skipping" line.
 3. The "Build" line.
 4. The "Error" line.

These 4 lines are ones we generate from within MGCB and the only ones we can use to parse build info. That plus the knowledge that content processing happens in sequence is all we can depend on.

We see an error message after a Clean/Skip/Build line... then that item error-ed.

We see any other line after Clean/Skip/Build... it is informational.

We can try to parse file and line info from any line that passes the regex parse for it.  But we cannot assume that all content processing will output good info like that.

That really is the best we can do i think.

**Comment by cra0zy** [comment]
The errors are not the thing I want to format, the thing I want to format is the output MGCB provides for Clean/Skip/Build etc, currently its not the easiest thing to either read or parse. 

For example, how about always outputting all the failed files at the end, that way no scrolling is needed to find what failed to compile.

Or how about having better verbosity on what its doing, like: 
```
Building: Car.x.... [Success]
Building: B.x.... [Failed]
Error: <error message>
Building: A.x.... [Success]
```

instead of doing:
```
Car.x
B.x: error: asdasdasdasdadsaas
A.x
```

**Comment by tomspilman** [comment]
> Or how about having better verbosity on what its doing

The formatting how it is now started as mimicking XNA's output, but we don't have to and i wouldn't have an issue improving it.  However what you are suggesting doesn't work how i see it.

```
Building: Car.x.... [Success]
Building: B.x.... [Failed]
```
The build line and the success/failed cannot be on the same line.  First you need a message to be emitted when building of an item starts... else you wouldn't know what is currently building.  Second it could spit out a bunch of warnings or errors before the build succeeds/fails.  So the build start has to be a line of its own.  Still i don't have a problem putting a wart on the start like "Building".

```
Error: <error message>
```
We [already do this](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MGCB/BuildContent.cs#L347) just formatted like VS does it's errors: `filename: error: message` or `filename(line): error: message`.  While i feel content building has no place in VS... i still want to retain its formatting for errors so line links still work.

> instead of doing:

That isn't really accurate to how our build logging works.  Here is a more accurate example:
```
Build started 3/11/2018 7:28:52 AM

Cleaning C:/Project/Content/Car.x
Skipping  C:/Project/Content/Logo.png
C:/Project/Content/Car.x
You could get some random info/warning text during content building.
It can be multi-line and formatted in any weird way the user chooses to log things.
C:/Project/Content/B.x
C:/Project/Content/B.x(123): error: asdasdasdasdadsaas
C:/Project/Content/Font.spritefont
C:/Project/Content/Font.spritefont: error: Importer 'FontDescriptionImporter' had unexpected failure!
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException: An error occured parsing. ---> System.Xml.XmlException: 'xmlns' is an unexpected token.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   blah blah blah
C:/Project/Content/A.x

Build 3 succeeded, 2 failed.

Time elapsed 00:00:00.87.
```

I don't see a lot to improve there other than maybe:
```
Build started 3/11/2018 7:28:52 AM

Cleaning C:/Project/Content/Car.x
Skipping  C:/Project/Content/Logo.png
Building C:/Project/Content/Car.x
You could get some random info/warning text during content building.
It can be multi-line and formatted in any weird way the user chooses to log things.
Building C:/Project/Content/B.x
C:/Project/Content/B.x(123): error: asdasdasdasdadsaas
Building C:/Project/Content/Font.spritefont
C:/Project/Content/Font.spritefont: error: Importer 'FontDescriptionImporter' had unexpected failure!
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException: An error occured parsing. ---> System.Xml.XmlException: 'xmlns' is an unexpected token.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   blah blah blah
Building C:/Project/Content/A.x

Build 3 succeeded, 2 failed.

Time elapsed 00:00:00.87.
```
But i honestly don't see how that improves much of anything.

**Comment by cra0zy** [comment]
Well the above are just few things that I would like changing, I'll write a proper set of changes a bit later, but for now.

> The build line and the success/failed cannot be on the same line. First you need a message to be emitted when building of an item starts... else you wouldn't know what is currently building. Second it could spit out a bunch of warnings or errors before the build succeeds/fails. So the build start has to be a line of its own. Still i don't have a problem putting a wart on the start like "Building".

You could:
- Send "Building: Car.x.... " when the build starts (without an end line)
- Write either "[Success]" or "[Failed]" + new line when the building of the file ends
- Write any error/warning messages from the build in a new line or post them later

> I don't see a lot to improve there other than maybe Building lines:

It would look like:
```
Build started 3/11/2018 7:28:52 AM

Cleaning C:/Project/Content/Car.x
Skipping C:/Project/Content/Logo.png
Building C:/Project/Content/Car.x............... [Success]
Building C:/Project/Content/B.x................. [Failed]
Building C:/Project/Content/Font.spritefont..... [Failed]
Building C:/Project/Content/A.x................. [Success]

Errors:

C:/Project/Content/B.x(123): error: asdasdasdasdadsaas

C:/Project/Content/Font.spritefont: error: Importer 'FontDescriptionImporter' had unexpected failure!
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException: An error occured parsing. ---> System.Xml.XmlException: 'xmlns' is an unexpected token.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   blah blah blah

Build 3 succeeded, 2 failed.

Time elapsed 00:00:00.87.
```

**Comment by tomspilman** [comment]
> Send "Building: Car.x.... " when the build starts (without an end line)

That is a little weird.  I wonder if `Process.OutputDataReceived` would support receiving that before the line ending.

> Write either "[Success]" or "[Failed]" + new line when the building of the file ends

So what happens when some importer/processor or a 3rd-party library does `Console.Write("Some message")`?

It just breaks the build message and the parsing in the pipeline tool?  Will it recover or crash?

> I think I would like them to appear twice more than just at the end

How does the new user (or the VS output window for that matter) not get confused by seeing errors twice?  

Can you point me at any other tool that emits error messages twice?


> Building C:/Project/Content/Car.x............... [Success]

So we pre-measure the length of all the file paths and figure out how many `....` we need to align the error/success messages.  Then what happens when an FBX references a texture and builds it and it is a longer path than the others?

I understand wanting to improve the logging to make parsing easier, but what you're suggesting here seems to be "make it pretty".  I can get behind some of that... making the raw MGCB log nicer to read would be ok.

I just think most of what you've suggested makes the code more complex with more possibilities of failure.

How it is now it mimics how almost all compilers on all platforms work.  Which i think is reasonable for what MGCB does.

**Comment by cra0zy** [comment]
> Can you point me at any other tool that emits error messages twice?

Yes, msbuild...:
```
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 21.96 ms for /home/harry/test/test.csproj.
Game1.cs(16,30): error CS0103: The name 'truae' does not exist in the current context [/home/harry/test/test.csproj]

Build FAILED.

Game1.cs(16,30): error CS0103: The name 'truae' does not exist in the current context [/home/harry/test/test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.69
```

> So we pre-measure the length of all the file paths and figure out how many .... we need to align the error/success messages. Then what happens when an FBX references a texture and builds it and it is a longer path than the others?

Nah, we just need terminal width to position passed/failed messages, its very easy to do.

**Comment by cra0zy** [comment]
> That is a little weird. I wonder if Process.OutputDataReceived would support receiving that before the line ending.

Data received from another process has nothing to do with new lines.

**Comment by nkast** [comment]
Let me jump in and give some examples of how the current system is inconsistent.
Consider the following cases:

```
context.Logger.LogWarning(null, input.Identity, "This is a Warning");
context.Logger.LogWarning(null, null, "This is another Warning");
throw new InvalidContentException("This is an Error", input.Identity);
```

Those will output the following:

```
P:/TestContent/test.fbx: This is a Warning
This is another Warning
P:/TestContent/test.fbx: This is an Error
```
 
Clearly we have a problem here. We can't tell which one is an error, a warning or just a message.
#5163 will output this:

```
P:/TestContent/test.fbx : warning : this is a Warning
P:/TestContent/test.fbx : warning : this is another Warning
P:/TestContent/test.fbx : error : this is an Error
```

That's what #5163 was about. To make MGCB output consistent and easy to parse.
It following the microsoft standard to make errors/warnings visible to Visual studio and easy to parse by  the pipeline or other 3rd party tools.

The only fancy thing is the last commit which handles MGFX output. Maybe we can find a better way to handle this.

Another thing I was not able to solve was multiline messages. I assume XNA/VS is not parsing the console output but attaches to a logger.  There is documentation on how to implement such a thing but before jumping into this I wanted to get the common cases fixed.
