### ISSUE TITLE
3.7.0.1465 - Crash when loading FBX files with Open Asset Importer

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#6277]
When I try to load a FBX model with Open Asset Importer, I get this exception:

```
Microsoft.Xna.Framework.Content.ContentLoadException
  HResult=0x80131500
  Message=Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline, Version=3.7.0.1465, Culture=neutral, PublicKeyToken=null]] (Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline]])
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(ContentReader reader)
   at Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at Sandbox1.Game1.LoadContent() in F:\_ScrachSpace\_Monogame\WinDesktop 3DModel Sandbox\Sandbox1\Sandbox1\Game1.cs:line 50
   at Microsoft.Xna.Framework.Game.Initialize()
   at Sandbox1.Game1.Initialize() in F:\_ScrachSpace\_Monogame\WinDesktop 3DModel Sandbox\Sandbox1\Sandbox1\Game1.cs:line 35
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Sandbox1.Program.Main() in F:\_ScrachSpace\_Monogame\WinDesktop 3DModel Sandbox\Sandbox1\Sandbox1\Program.cs:line 18

```

Something to do with `Microsoft.Xna.Framework.Content.ReflectiveReader`.

The FBX model loads fine with FBX Importer.

The reason I want to try using Open Asset Importer is because the current version of FBX Importer is processing the specular lighting in a different way than previous versions, giving a "light burnt" look to our current renders.

I don't know if the specular change in FBX Importer is a fix, but it certainly looks different than how XNA looked like.

Example file failing to render: [Content.zip](https://github.com/MonoGame/MonoGame/files/1894503/Content.zip)

As a side note, if Monogame Framework crashes when trying to load the file, I would suggest the content pipeline processor to try reload the assets it creates, just to ensure they crash at build time and not at runtime.

Related to #6179 and https://github.com/MonoGame/MonoGame/commit/35c152856d3aa9585219c1da195c61e096430288

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1465

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by GoldenThumbs** [comment]
Would like to add that I have this issue with every model format. I have to load OBJs with the FBX importer (not sure why that works, someone who is more familiar maybe able to tell me).

**Comment by roy-t** [comment]
This should be closed as a duplicate of https://github.com/MonoGame/MonoGame/issues/6179 to keep everything tidy :).
