### ISSUE TITLE
Android projects cannot initialize AudioDevice

### ISSUE THREAD

**Issue by MattiKloepper** [MonoGame/MonoGame#6382]
I'm experiencing a problem with running android projects in Monogame 3.7.0.1641. To narrow things down I have created a completely new Monogame Android through the current Visual Studio 2017 template.

In the main activity the template creates a new Game object with "var g = new Game1();". Running this code on either an Android emulator (Oreo 8.0 and 8.1 devices created with the Android Device Manager) or an my Samsung Galaxy Tab throws an Exception in the Game-Class constructor.

Exception: Microsoft.Xna.Framework.Audio.NoAudioHardwareException
Inner Exception: System.NullReferenceException
Message: "OpenAL device could not be initialized."
Source: MonoGame.Framework
Stacktrace:
  at Microsoft.Xna.Framework.Audio.OpenALSoundController.OpenSoundController () [0x00031] in <b488439325ec489f8bc723f2a162f479>:0 
  at Microsoft.Xna.Framework.Audio.OpenALSoundController..ctor () [0x00011] in <b488439325ec489f8bc723f2a162f479>:0 
  at Microsoft.Xna.Framework.Audio.OpenALSoundController.get_GetInstance () [0x00007] in <b488439325ec489f8bc723f2a162f479>:0 
  at Microsoft.Xna.Framework.AndroidGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x00060] in <b488439325ec489f8bc723f2a162f479>:0 
  at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00000] in <b488439325ec489f8bc723f2a162f479>:0 
  at Microsoft.Xna.Framework.Game..ctor () [0x001fb] in <b488439325ec489f8bc723f2a162f479>:0 
  at Test.Droid.Game1..ctor () [0x00000] in [...]\Test.Droid\Game1.cs:16 
  at Test.Droid.Activity1.OnCreate (Android.OS.Bundle bundle) [0x0000a] in [...]\Test.Droid\Activity1.cs:24
  
The android emulators as well as the physical Samsung tablet produces sounds without problems in other apps or the OS.

Is there anything I can do to repair this problem or at least to deactivate the AudioHardwareInitialization?

Kind regards,
Matti

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Android

**Comment by mrhelmut** [comment]
Would you mind trying to use a MonoGame older than this commit (or revert it)? https://github.com/MonoGame/MonoGame/commit/017c1a7629d2c496487557520ff57d246cd6250a

**Comment by MattiKloepper** [comment]
Very well. Seems like that has been some sort of installation issue on my machine. Since I created the project with build 3.7.0.1641 installed vie the Setup program I switched to NuGet. Problem still occurs with older builds.
I than removed the Monogame and OpenTK references from the Project and switch back to 1641 via Nuget. It is working now?!

Even if I create a new project without Nuget this works now, too.

I guess there has been some probmles with incrementally upgrading my nuget packages through the last weeks. Just sorry that I can't recreate the problem. Thanks for your Suggestion anyway :-)

**Comment by mrhelmut** [comment]
No worry, glad it worked.
The nuget uses an older version, so it may still be an issue on more recent work. There has been a bunch of refactoring lately that may have introduce it.

If you happen to try again a nightly build, please drop by to confirm if it worked.

**Comment by MattiKloepper** [comment]
Sorry for the hassle. I have been quite curious About the cause of this Problem and did some completly clean reinstallations.
New Solution in Visualstudio 2017 with just a single MonoGame Android Project created from the template an no changes.
Just using the installed libraries, no nuget packages.

MonaGame version changes have been performed via uninstallation, reboot, cleaning the solution in Visualstudio and rebuilding.

This works for up to MonoGame 3.7.1608 but produces the originally described Problem from 3.7.1624 onward. Will try the intermediate versions now to pinpoint the Problem to a specific build.

**Comment by MattiKloepper** [comment]
I narroed it down. The problem has been intruduced with build 3.7.1622.
With build 3.7.1621 the game constructor works without a problem.

**Comment by cra0zy** [comment]
> With build 3.7.1621

That's not a development build, its a PR build: http://teamcity.monogame.net/viewType.html?buildTypeId=MonoGame_DevelopWin&tab=buildTypeHistoryList&branch_MonoGame=__all_branches__


Test out builds 3.7.0.1620 and 3.7.0.1614 if you have time.

**Comment by MattiKloepper** [comment]
That build has merged some changes from @nkast . espacially some NullDeviceTests. May one of those Tests throws the Basic NullReferenceException?

**Comment by cra0zy** [comment]
> That build has merged some changes from @nkast . espacially some NullDeviceTests. May one of those Tests throws the Basic NullReferenceException?

No, no it has not, it was build against nkasts branch, not against develop branch. Build bot builds individuals PRs as well.

**Comment by MattiKloepper** [comment]
Ah ok, sorry.
As you proposed I tested builds 1620 and 1614.

3.7.01614 works fine but 3.7.0.1620 throws the exception.

**Comment by cra0zy** [comment]
Guessed as much, once I get home I'll look into it.

**Comment by cra0zy** [comment]
I have a fix for this locally, tho still need to fix one other thing before submitting.

**Comment by cra0zy** [comment]
PR for fixing this is up.

**Comment by MattiKloepper** [comment]
That has been fast. Thanks! Will try that out as soon as possible.

Mit freundlichen Grüßen,
Matthias Klöpper

--
Matthias Klöpper
Hügelstrasse 53
40589 Düsseldorf

Mobilfunk: 0171 - 1276059

Von: Harry
Gesendet: Samstag, 28. Juli 2018 12:06
An: MonoGame/MonoGame
Cc: Matti; State change
Betreff: Re: [MonoGame/MonoGame] Android projects cannot initialize AudioDevice (#6382)

PR for fixing this is up.

**Comment by MattiKloepper** [comment]
Works fine for me now. Thanks a lot.

**Comment by nsnsns** [comment]
also, guys - it seems the 3.7.0.1625 build works ok on Lava Pixel V1 - using Pure Android (Android One) - while it crashes on Xiaomi Mi Max Prime which uses MiUI just as it crashes on @MattiKloepper Samsung Tab which uses TouchWiz UI.

However, I used the 3.7.0.1679 build from NuGet - and rebuilt project-- and it works perfect - both on device using AndroidOne and on Xiaomi MiMax Prime - which uses MiUI

**Comment by TheMaxPirat** [comment]
Running empty Monogame Android VS template on real device throw NoAudioHardwareException  immediately. Full error is:

> android.runtime.JavaProxyThrowable: Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005): OpenAL device could not be initialized. ---> System.NullReferenceException: Object reference not set to an instance of an object
>   at Microsoft.Xna.Framework.Audio.OpenALSoundController.OpenSoundController () [0x00000] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.Audio.OpenALSoundController.OpenSoundController () [0x00031] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.Audio.OpenALSoundController..ctor () [0x00011] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.Audio.OpenALSoundController.get_GetInstance () [0x00007] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.AndroidGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x00060] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00000] in <37350412498b49e2b272843ac85c135f>:0 
>   at Microsoft.Xna.Framework.Game..ctor () [0x00213] in <37350412498b49e2b272843ac85c135f>:0 
>   at AndroidCrash.Game1..ctor () [0x00000] in <ec213756e4a7413484b26d85b43d40e5>:0 
>   at AndroidCrash.Activity1.OnCreate (Android.OS.Bundle bundle) [0x00007] in <ec213756e4a7413484b26d85b43d40e5>:0 
>   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <2a702fbfc33d4bcd85ca3545ab14337e>:0 
>   at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
> 	at md584d9907c8a2f09818a2e46e13bb2ce80.Activity1.n_onCreate(Native Method)
> 	at md584d9907c8a2f09818a2e46e13bb2ce80.Activity1.onCreate(Activity1.java:29)
> 	at android.app.Activity.performCreate(Activity.java:6852)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
> 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:165)
> 	at android.app.ActivityThread.main(ActivityThread.java:6365)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)

The issue occurs with both nuget version (3.7.0.1708 and 3.7.0.1681-develop). 

I cloned and checkout some older commits (I'm new at this stuff, sorry if I'm using wrong terminology). Everything before https://github.com/MonoGame/MonoGame/commit/017c1a7629d2c496487557520ff57d246cd6250a works, everything after doesn't, including this commit https://github.com/MonoGame/MonoGame/commit/fc0afb383b64e8210256ec4347e36b83fca8fee1 

Based on the last comment and my experience it may be related to Xiaomi phones, maybe even exclusive to it. 

I was able to test it on Xiaomi Note 4, Xiaomi Redmi 5 exception occuir on both. But it doesn't with Android emulator (Oreo 8.1). Sadly I don't have any other Android phone, so I can't test anything else.
