### ISSUE TITLE
MonoGameContentReference fails if path contains a # character

### ISSUE THREAD

**Issue by PikeUK** [MonoGame/MonoGame#6603]
My MonoGame project was located at C:\Users\\{username}\Documents\C#\\{solution}. I added a Content project using the MonoGame.Content.Builder NuGet package but when I tried to build I got the following error:
~~~~
Error		The "GetMGCBTask" task failed unexpectedly.
System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\{username}\build\MGCB.zip'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at MSBuildTasks.GetMGCBTask.LocateMGCBFromNuget()
   at MSBuildTasks.GetMGCBTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CarCombatGame			
~~~~
After renaming the C# folder in my path to CSharp the error no longer occurs and the project successfully builds and runs.

#### What version of MonoGame does the bug occur on:
- MonoGame.Content.Builder 3.7.0.9 (NuGet package)

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDX & Content (via NuGet)

**Comment by Jjagg** [comment]
@cra0zy This is your content builder branch. Looks like it doesn't escape special chars in the Uri.

**Comment by harry-cpp** [comment]
Gonna close this as there is a new MGCB nuget in the develop branch.
