### ISSUE TITLE
OpenAL SoundEffect crash - failure to delete buffers

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6622]
Every now and then, I encounter a crash with OpenAL failing to delete a buffer because it's in-use. This happens only on SoundEffects loaded through the ContentManager when I exit the game and call `Unload()` on all my content. All my `SoundEffectInstances` are pooled, and they're stopped and disposed, if they haven't been already, before the content is unloaded.

Full stack trace:
```
Unhandled Exception: System.InvalidOperationException: Failed to delete buffer. (Reason: InvalidOperation)
at Microsoft.Xna.Framework.Audio.ALHelper.CheckError(String message, Object[] args) in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\OpenALSoundController.cs:line 38
at Microsoft.Xna.Framework.Audio.OALSoundBuffer.Dispose(Boolean disposing) in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\OALSoundBuffer.cs:line 92
at Microsoft.Xna.Framework.Audio.OALSoundBuffer.Dispose() in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\OALSoundBuffer.cs:line 75
at Microsoft.Xna.Framework.Audio.SoundEffect.PlatformDispose(Boolean disposing) in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\SoundEffect.OpenAL.cs:line 231
at Microsoft.Xna.Framework.Audio.SoundEffect.Dispose(Boolean disposing) in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\SoundEffect.cs:line 458
at Microsoft.Xna.Framework.Audio.SoundEffect.Dispose() in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Audio\SoundEffect.cs:line 440
at Microsoft.Xna.Framework.Content.ContentManager.Unload() in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Content\ContentManager.cs:line 468
at Redacted.AssetManager.CleanUp() in D:\Documents\Redacted\AssetManager.cs:line 86
at Redacted.Engine.UnloadContent() in D:\Documents\Redacted\Engine.cs:line 149
at Microsoft.Xna.Framework.Game.DoExiting() in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Game.cs:line 695
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Game.cs:line 401
at Microsoft.Xna.Framework.Game.Run() in D:\Documents\MonoGame\MonoGame\MonoGame.Framework\Game.cs:line 369
at Redacted.Program.Main() in D:\Documents\Redacted\Program.cs:line 22
```
It's linked to this part of `OALSoundBuffer`:
```
// Release unmanaged resources
if (AL.IsBuffer(openALDataBuffer))
{
    ALHelper.CheckError("Failed to fetch buffer state.");
    AL.DeleteBuffers(1, ref openALDataBuffer);
    ALHelper.CheckError("Failed to delete buffer.");
}
```
When it crashes seems totally random. I can't find a reliable way to reproduce it.

#### What version of MonoGame does the bug occur on:
- Latest develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by tdeeb** [comment]
Update: this is happening even if I don't explicitly call `Unload` on my content. I verified I'm not accessing any sounds while the game is exiting, and this started only recently despite the code in question not being touched for a while.

**Comment by mrhelmut** [comment]
The unload behavior hasn't been modified in a while, about a couple years I guess.

MonoGame is automatically stopping and disposing pooled instances upon termination. The error is maybe related to them being disposed twice if you already do that (which should already be prevented, but maybe we're missing a code path). Though ```IsBuffer``` should handle that case....

Let me know if you come up with a test project. As-is it's going to be very hard to identify, I never stumbled upon it despite having an intensive use of SoundEffect.

**Comment by tdeeb** [comment]
I'm having trouble replicating the issue in a test project, but I've narrowed it down slightly. It only happens when I play sound effects in my game, not music, despite both using `SoundEffects` and `SoundEffectInstances`.

Next I'd like to see which sounds its crashing on to further dig into the issue, but I need to see which `SoundEffect` the `OALSoundBuffer` belongs to and I'm not sure how to step through and debug that with the MonoGame DLLs hiding the code (even with the PDB files, which don't let me go look into definitions).

**Comment by mrhelmut** [comment]
What happens if you trigger about 100 SoundEffect.Play() at once and unload+exit the application a couple frames later?
This should expose the issue more.

Are you eventually using threads? (it may be a race condition on a disposal)

**Comment by tdeeb** [comment]
All right, I have a test program that works semi-reliably. The included `SoundManager` is extremely close to what I do to play sounds.
* Press ESC to have it play a bunch of sounds then unload the content
* There's a catch to getting it throwing the error: set a breakpoint on line 80 of Game1.cs while it's playing some sounds, wait a bit, then continue, and you should get the error
[TestOpenALIssue.zip](https://github.com/MonoGame/MonoGame/files/2751769/TestOpenALIssue.zip)

No threading is involved in my game. I noticed `RenderTarget2D` on OpenGL waits for the UI thread to dispose since OpenGL doesn't support multithreading, so I removed all RenderTargets from my game and still got the issue.

Eventually, I tried a fix and now really think the issue is that we're not unqueuing the buffers before deleting them. I changed `OALSoundBuffer.Dispose` to this and haven't had any issues at all since:
```
protected virtual void Dispose(bool disposing)
        {
            if (!_isDisposed)
            {
                if (disposing)
                {
                    // Clean up managed objects
                }
                // Release unmanaged resources
                if (AL.IsBuffer(openALDataBuffer))
                {
                    ALHelper.CheckError("Failed to fetch buffer state.");
                    AL.SourceUnqueueBuffers(openALDataBuffer, 1);
                    ALHelper.CheckError("Something went wrong");
                    AL.DeleteBuffers(1, ref openALDataBuffer);
                    ALHelper.CheckError("Failed to delete buffer.");
                }

                _isDisposed = true;
            }
        }
```

**Comment by tdeeb** [comment]
Okay, I think I'm officially dumb. The entire time I had a Debug version of MonoGame that I built. The issue is not present in a Release version.

**Comment by mrhelmut** [comment]
It may still be relevant. If it doesn't happen on release code, it probably means that the error checking is less strict and that the error would still silently happen. It probably can't harm to add that unqueue.

Calls to ```CheckError``` are ignored in release mode.

**Comment by tdeeb** [comment]
That's a good point. Unfortunately, the unqueue didn't work in Debug when I tested it. I suspect we need the source ID and not the buffer.

**Comment by tdeeb** [comment]
I might give this another go over the next few days and fix it on Debug. I'm thinking of using [alSourcei](https://github.com/kcat/openal-soft/wiki/Programmer%27s-Guide#alsourcei-1) with a 0 value to detach the source from the buffer.

**Comment by tdeeb** [comment]
It looks like we are [unbinding the buffers properly](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.OpenAL.cs#L184) in `PlatformStop`. In my case, all the SoundEffectInstances are stopped and disposed, and the error occurs when disposing the `SoundEffect` because it's still attached to a source.

On that note, the version of OpenAL Soft [MonoGame is using](https://github.com/KonajuGames/openal-soft/blob/master/OpenAL32/alBuffer.c#L78) is 1.16, which is a bit behind and quite different from [the official one, which is currently at 1.19.1](https://github.com/kcat/openal-soft/blob/master/OpenAL32/alBuffer.cpp#L457). There have been several fixes and improvements since.

**Comment by mrhelmut** [comment]
Yeah, we should update it at some point. The thing is we have to build it ourselves for all systems because the binaries from the official website have a dependencies towards the MSCV6 runtime (while it should be statically linked to avoid dependencies mismatch errors).

**Comment by tdeeb** [comment]
@tomspilman @cra0zy @Jjagg Any thoughts on this? Is there a procedure to upgrading MonoGame dependencies, such as OpenAL?

**Comment by Jjagg** [comment]
Tom set up CI for some of our native dependencies to build them the way we need, but he hasn't done that for OpenAL Soft yet. Dependencies are first updated in the dependencies repo [MonoGame.Dependencies](https://github.com/MonoGame/MonoGame.Dependencies) which is a submodule in this repo, so afterwards the submodule needs to be updated here. (we should improve on that IMO)

**Comment by tdeeb** [comment]
I took another look at this after seeing [this thread](http://community.monogame.net/t/openalsoundcontroller-slowly-runs-out-of-available-sources/11714) in the community forums.

I noticed that `PlatformDispose` in `SoundEffectInstance.OpenAL` does not actually do anything. The sources get recycled back to the `availableSourcesCollection` **only** when `Stop` is called, but the `SoundEffectInstancePool` manually calls `Stop` in its update loop if the sound is disposed or stopped. Here's the code in question:
```
if (inst.IsDisposed || inst.State == SoundState.Stopped || (inst._effect == null && !inst._isDynamic))
{
#if OPENAL
    if (!inst.IsDisposed)
    inst.Stop(true); // force stopping it to free its AL source
#endif
    Add(inst);
    continue;
}
```
It looks like it does this here so the `SoundEffectInstance` pool can know when to add it back, but I see an issue with this. If `Stop` is not called on the `SoundEffectInstance` before `SoundEffectPool.Update` runs and the OALSoundBuffer is disposed, it will throw the exception since the instance is still in use. Important to note is there is a lock on the `availableSourcesCollection`, which occurs in `OpenALSoundController.FreeSource`, which may play a factor in delaying cleanup.

Is there a way we can improve this so we don't need to rely on the update loop freeing the source?

**Comment by Jjagg** [comment]
We should make `PlatformDispose` in `SoundEffectInstance.OpenAL` release the source. At a glance I think we can just have it call `PlatformStop()`.

**Comment by tdeeb** [comment]
Absolutely! I'll find some time once it's up; thanks!

**Comment by Jjagg** [comment]
@tdeeb PR is up! #6813
