### ISSUE TITLE
Content Pipeline Tool crashes on open/save file dialogs

### ISSUE THREAD

**Issue by Kyle873** [MonoGame/MonoGame#6693]
Basically what it says on the tin. Whenever I try to open a file open/save dialog in the Content Pipeline Tool, it just crashes.

Trying to use File > Import, right-click and Add > Existing Item..., or adding a new reference reproduces this problem for me every single time. I have no idea what could be causing this nor what more information to provide that would be helpful beyond the stack trace.

Just out of curiosity I also tried on the 3.7.1 release and the problem still persists.

``
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Win32.OpenFileDialog.CreateVistaDialog()
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog(Window owner)
   at Eto.Wpf.Forms.WpfCommonDialog`2.ShowDialog(Window parent)
   at MonoGame.Tools.Pipeline.MainWindow.ChooseContentFile(String initialDirectory, List`1& files)
   at MonoGame.Tools.Pipeline.PipelineController.Include()
   at Eto.Forms.Command.OnExecuted(EventArgs e)
   at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
   at Eto.Forms.MenuItem.OnClick(EventArgs e)
   at Eto.Forms.MenuItem.Callback.OnClick(MenuItem widget, EventArgs e)
   at Eto.Wpf.Forms.Menu.MenuItemHandler`3.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args)
``

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.341

#### What operating system are you using:
- Windows 10 Version 1809

#### What MonoGame platform are you using:
- DesktopGL

**Comment by Kyle873** [comment]
After doing a bit of digging, I've found a solution to the problem. I found this [SO post](https://stackoverflow.com/questions/29929862/exception-from-hresult-0x80040111-class-e-classnotavailable) which details that the root cause has to do with the visual themes being turned off. I use a high contrast theme due to vision problems, so that means the only way for me to use the Content Pipeline Tool is to re-enable the visual themes. This should really be looked into because it's a legitimate usability and accessibility concern. That also means this issue should be easily reproducable. All one would need to do is disable visual themes, such as by enabling high contrast.

**Comment by cra0zy** [comment]
@cwensley Pinging you as this might be an issue with Eto Forms WPF backend in general, gonna test it out tomorrow if I get some time.

**Comment by Jjagg** [comment]
@harry-cpp did this ever get fixed?

**Comment by harry-cpp** [comment]
Nope.
