### ISSUE TITLE
XAudio2 crash on audio file set below Best quality in Content Pipeline

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6701]
I have an MP3 file processed as a Sound Effect. To reduce build size, I set the quality to Medium in the content pipeline. On DesktopGL builds, I have no issues, but on a WindowsDX build, the game always crashes when trying to play that sound effect. The game also crashes if the quality is set to low. However, when I set the quality to Best, it does not crash.

I did indeed change the platform to Windows in the content pipeline before processing the content for the Windows build.

```
Stack Trace:
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.XAudio2.CreateSourceVoice_(SourceVoice sourceVoiceOut, IntPtr sourceFormatRef, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callbackRef, Nullable`1 sendListRef, Nullable`1 effectChainRef)
   at SharpDX.XAudio2.SourceVoice.CreateSourceVoice(XAudio2 device, WaveFormat sourceFormat, VoiceFlags flags, Single maxFrequencyRatio, IntPtr callback, EffectDescriptor[] effectDescriptors)
   at Microsoft.Xna.Framework.Audio.SoundEffect.PlatformSetupInstance(SoundEffectInstance inst)
   at Microsoft.Xna.Framework.Audio.SoundEffect.CreateInstance()
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7 (develop)

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by mrhelmut** [comment]
Do you happen to have a SharpDX error code with the exception message?

Does it crash with absolutely all files and only some of them (if so, could you share one that fails?).

**Comment by tdeeb** [comment]
This is what I can gather from the crash:

```
HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
```

Later today or tomorrow, I'll test on an empty project with a few files and report back.

**Comment by tdeeb** [comment]
Here's a barebones project reproducing the issue. Simply load up the game and press the Space bar to crash it.
[TestXAudioCrash.zip](https://github.com/MonoGame/MonoGame/files/3050144/TestXAudioCrash.zip)

You can change the content import settings and see that setting it to Best won't crash but Medium and Low does.

The sound used is royalty-free from [here](https://freesound.org/people/Hypnochick/sounds/465282/).

**Comment by mpokrzywa** [comment]
Medium and Low settings produce adpcm wave file with SamplesPerBlock higher then 512.
FFmpeg fault.

**Comment by tdeeb** [comment]
> 
> 
> Medium and Low settings produce adpcm wave file with SamplesPerBlock higher then 512.
> FFmpeg fault.

If I manually convert the file with the same settings and play it via an audio player (Ex. Windows Media Player), it plays just fine.

**Comment by mpokrzywa** [comment]
Sorry that I did not make myself clear.
XAudio2 uses a modified version of the Microsoft ADPCM codec. FFmpeg output vanilla Microsoft ADPCM file. The difference is in SamplesPerBlock, where XAudio2 smallest block size is 32 samples, and the highest is 512 samples. Microsoft ADPCM can have much larger size, FFmpeg output 1k samples. 
XAudio2 library is very strict about the format of the data becuase xbox uses the same library and decode sound via hardware dsp so creating XAudio2 object without proper adpcm data will end with an exception like in your example.

**Comment by tdeeb** [comment]
Thanks for the explanation! Would we need to lower the settings in FFmpeg for platforms using XAudio2 to fix this?

**Comment by tdeeb** [comment]
Thanks for the explanation! Would we need to lower the settings in FFmpeg for platforms using XAudio2 to fix this?

**Comment by squarebananas** [comment]
As FFmpeg haven't fix this (nkast first reported the issue to them 7 years ago) and now that MonoGame.Tool.FFmpeg exists, this issue can finally be fixed.

These changes allow medium/low quality audio files to be built and played on the WindowsDX platform.

MonoGame.Tool.FFmpeg\build\BuildWIndowsTask.cs
After FFmpeg distclean:

```
context.ReplaceTextInFiles("./ffmpeg/libavcodec/adpcmenc.c", "av_log(avctx, AV_LOG_ERROR, \"block size must be power of 2\\n\");", "");
context.StartProcess(shellCommandPath, processSettings);
context.ReplaceTextInFiles("./ffmpeg/libavcodec/adpcmenc.c", "return AVERROR(EINVAL);", "");
context.StartProcess(shellCommandPath, processSettings);
```

MonoGame.Framework.Content.Pipeline\Audio\DefaultAudioProfile.cs
Add block size argument to codec name:

`ffmpegCodecName = "adpcm_ms -block_size 70";`

A couple of points to consider though:

1) I have only tested this on Windows. Alterations to the BuildLinuxTask and BuildMacOSTask code as well as testing the MGCB editor on those platforms would also be necessary.
2) **FAudio appears to work with MonoGame built medium/low quality audio files already.** If FAudio is due soon is it still worthwhile spending extra time fixing this?

**Comment by mrhelmut** [comment]
> 2\. If FAudio is due soon is it still worthwhile spending extra time fixing this?

If the fix is as simple as that, I think it is worthwhile. Thanks for looking into that!
