### ISSUE TITLE
Self-contained Core application crashes on Ubuntu

### ISSUE THREAD

**Issue by Ellpeck** [MonoGame/MonoGame#7101]
When using the newest version of MonoGame.Framework.DesktopGL.Core (`3.8.0.13`), the following issue occurs: When publishing a self-contained app for Linux using `dotnet publish -r linux-x64`, it crashes immediately on startup when run on Ubuntu 18.04:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Sdl' threw an exception.
 ---> System.Exception: Failed to load library: libSDL2-2.0.so.0
   at MonoGame.Utilities.FuncLoader.LoadLibraryExt(String libname)
   at Sdl..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.SdlGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
   at MLEMDesktopGLCoreTest.GameImpl..ctor() in C:\Users\me\Desktop\MLEMDesktopGLCoreTest\MLEMDesktopGLCoreTest\GameImpl.cs:line 7
   at MLEMDesktopGLCoreTest.Program.Main() in C:\Users\me\Desktop\MLEMDesktopGLCoreTest\MLEMDesktopGLCoreTest\Program.cs:line 5
Aborted (core dumped)
```
When publishing the same project for `osx-x64` or `win-x64`, it runs without errors on its respective system.

Note that I also tested this with an almost entirely blank template project, and the same behavior occured.

#### What version of MonoGame does the bug occur on:
- MonoGame.Framework.DesktopGL.Core 3.8.0.13

#### What operating system are you using:
- Windows to build
- Ubuntu 18.04 where the issue occurs

#### What MonoGame platform are you using:
- DesktopGL.Core

**Comment by harry-cpp** [comment]
For now you can make a "x64" folder, and move the sdl and openal libraries there and it will work.
