### ISSUE TITLE
Unable to build SpriteFonts

### ISSUE THREAD

**Issue by Dokug** [MonoGame/MonoGame#7172]
When generating a brand new SpriteFont File via the MGCB, the build process of the MGCB completes, but launching the project (without having changed anything other than adding and building a .spritefont File via MGCB) fails with the following error:
```
1>C:/Users/[...]/source/repos/MCDU/Content/Arial.spritefont
1>	Building Font C:\WINDOWS\Fonts\arial.ttf
1>C:/Users/[...]/source/repos/MCDU/Content/Arial.spritefont : error : Processor 'LocalizedFontProcessor' had unexpected failure!
1>System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
1>   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
1>   at SharpFont.Library..ctor()
1>   at Microsoft.Xna.Framework.Content.Pipeline.Graphics.SharpFontImporter.Import(FontDescription options, String fontName) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Graphics\Font\SharpFontImporter.cs:line 29
1>   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.ImportFont(FontDescription options, Single& lineSpacing, Int32& yOffsetMin, ContentProcessorContext context, String fontName) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Processors\FontDescriptionProcessor.cs:line 186
1>   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process(FontDescription input, ContentProcessorContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Processors\FontDescriptionProcessor.cs:line 79
1>   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentProcessor.cs:line 60
1>   at MonoGame.Framework.Content.Pipeline.Builder.PipelineProcessorContext.Convert[TInput,TOutput](TInput input, String processorName, OpaqueDataDictionary processorParameters) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineProcessorContext.cs:line 54
1>   at Microsoft.Xna.Framework.Content.Pipeline.Processors.LocalizedFontProcessor.Process(LocalizedFontDescription input, ContentProcessorContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Processors\LocalizedFontProcessor.cs:line 92
1>   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentProcessor.cs:line 60
1>   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 717
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by harry-cpp** [comment]
Just to confirm, your system is 64 bit?

**Comment by Dokug** [comment]
Yes, 64 Bit

**Comment by SoundAxis** [comment]
I was running into the same issue on my 64bit machine but was able to resolve it by swapping out the DLL, used the bin/msvc12/x64/freetype6.dll from the SharpFont.Dependencies.2.6 nuget.

And interesting note, is I that I also had to do this on a non-MonoGame project that was using QuickFonts/SharpFonts. Same dll swap for both.

**Comment by Dokug** [comment]
I've got a clean new project, with only the Monogame and 2 small nugets installed.
After building the spritefont, the problem occurs.
There is no code referencing Test.spritefont (or any spritefont for that matter)

![grafik](https://user-images.githubusercontent.com/63102276/83324099-1b32d680-a263-11ea-8456-e3e3f58236b5.png)

**Comment by Jjagg** [comment]
@harry-cpp This is a bit of a weird one. Maybe just caught the content build task at a bad time during the transition? I don't think this is still happening.

**Comment by harry-cpp** [comment]
Yup! Probably installed a 32 bit version on dotnet sdk on the machine, however the task is no longer dependent on dotnet.
