### ISSUE TITLE
Cannot import 3D models using mgcb-editor

### ISSUE THREAD

**Issue by sudoDavi** [MonoGame/MonoGame#7234]
I'm trying to follow some 3d tutorials for MonoGame and I cannot import 3d models into the Content file, it gives the following error when trying to import a **.fbx** file
```
 Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.so, error detail:
  Assimp64.so: cannot open shared object file: No such file or directory
     at Assimp.Unmanaged.AssimpLibraryLinuxImplementation.NativeLoadLibrary(String path)
     at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
     at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
     at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
     at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
     at Assimp.AssimpContext.CreateConfigs()
     at Assimp.AssimpContext.PrepareImport()
     at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
     at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\OpenAssetImporter.cs:line 291
     at Microsoft.Xna.Framework.Content.Pipeline.FbxImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\FbxImporter.cs:line 24
     at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentImporter.cs:line 45
     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 669
```
I've also seen it occur with a **.x** file and it gives the following error
```
Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.so, error detail:
  Assimp64.so: cannot open shared object file: No such file or directory
     at Assimp.Unmanaged.AssimpLibraryLinuxImplementation.NativeLoadLibrary(String path)
     at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
     at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
     at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
     at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
     at Assimp.AssimpContext.CreateConfigs()
     at Assimp.AssimpContext.PrepareImport()
     at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
     at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\OpenAssetImporter.cs:line 291
     at Microsoft.Xna.Framework.Content.Pipeline.XImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\XImporter.cs:line 32
     at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentImporter.cs:line 45
     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 669
```
They are all related to this **Assimp64.so** library, I've seen another issue in here about it #3599, followed the procedure listed by @harry-cpp and it did not work.
As a matter of fact here is the output of the command he showed to test if I had the proper libraries installed
```strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
So it seems I have a **libstdc++6** that supports  **GLIBCXX_3.4.20**

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8? (current development branch)

#### What operating system are you using:
- Pop_Os! 20.04 (Ubuntu 20.04)

#### What MonoGame platform are you using:

- DesktopGL

**Comment by jnoyola** [comment]
Probably related to #7229
