### ISSUE TITLE
ContentLoadException for imported collada models since 3.8 upgrade

### ISSUE THREAD

**Issue by AliciaRaven** [MonoGame/MonoGame#7313]
Hello
In my game I reference the content pipeline to allow for user created content to be imported at runtime. Since I upgraded to 3.8, when my game imports a collada model and attempts to load the model, the following exception is thrown...

> Microsoft.Xna.Framework.Content.ContentLoadException
  HResult=0x80131500
  Message=Error loading shared resource. Expected type Effect, received type MaterialContent
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Content.ContentReader.<>c__DisplayClass32_0`1.<ReadSharedResource>b__0(Object v)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)

The import settings are as follows..

`S_Importer      = "OpenAssetImporter";
S_Processor     = "ModelProcessor";

_processorParams.Add("ColorKeyColor", "0, 0, 0, 0");
_processorParams.Add("ColorKeyEnabled", "False");
_processorParams.Add("DefaultEffect", "BasicEffect");
_processorParams.Add("GenerateMipmaps", "True");
_processorParams.Add("GenerateTangentFrames", "False");
_processorParams.Add("PremultiplyTextureAlpha", "True");
_processorParams.Add("PremultiplyVertexColors", "True");
_processorParams.Add("ResizeTexturesToPowerOfTwo", "False");
_processorParams.Add("RotationX", "0");
_processorParams.Add("RotationY", "0");
_processorParams.Add("RotationZ", "0");
_processorParams.Add("Scale", "1");
_processorParams.Add("SwapWindingOrder", "False");
_processorParams.Add("TextureFormat", "DxtCompressed");`

Thanks

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641
- MonoGame Content Pipline 3.8.0.1641

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
Please use the FbxImporter instead of the assimp importer (even for non-fbx files). Duplicate of #6179.

**Comment by AliciaRaven** [comment]
Changed to FbxImporter and now model loading fails because the textures are not found. They are created inside the source file directory not the export file directory.

**Comment by Jjagg** [comment]
@harry-cpp You know what changed here?

**Comment by harry-cpp** [comment]
No idea.

**Comment by tomspilman** [comment]
> Changed to FbxImporter and now model loading fails because the textures are not found. They are created inside the source file directory not the export file directory.

@AliciaRaven we know you're using the FbxImporter, but are you using a custom model processor or the stock MG `ModelProcessor` ?

Seems like it could be a bug in either the `FbxImporter` or `ModelProcessor` to me.

We could add in another unit test here...

https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Tools.Tests/ModelProcessorTests.cs

... to test this situation and figure out the bug.

**Comment by Jjagg** [comment]
Intuitively it seems like this is a change in where we set the working directory for the content pipeline.

**Comment by AliciaRaven** [comment]
Here is some extra info, i hope it helps. It seems some where a path is built using parts from both source and output paths.

Create PipelineManager Giving Path..
D:\My Project\bin\Debug\netcoreapp3.1\Content\Temp\

Build Content Source Path
D:\Asset Store\Test Imports\Tree\Tree.dae

Build Content Output Path
D:\My Project\bin\Debug\netcoreapp3.1\Content\Temp\Tree.xnb

Now loading the model throws the following exceptions

Inner Exception 1:
FileNotFoundException: Content\Asset Store\Test Imports\Tree\TreeTexture2_0.xnb

The path above starts with Content folder which is part of output path, then the other folders are from the input path.

Inner Exception 2:
DirectoryNotFoundException: Could not find a part of the path 'D:\My Project\bin\Debug\netcoreapp3.1\Content\Asset Store\Test Imports\Tree\TreeTexture2_0.xnb'.

The path in the second exception begins with part of the source path and ends in part of the output path.

And the source folder now contains the texture xnb files.

**Comment by harry-cpp** [comment]
The following is also kind of connected: https://github.com/MonoGame/MonoGame/issues/7330

**Comment by AliciaRaven** [comment]
> 
> 
> Intuitively it seems like this is a change in where we set the working directory for the content pipeline.

This appears to be correct. The issue seems to be changes in BuildContent.cs where the PipelineManager sets Working directory and then all following code that uses Path.GetFullPath returns based on that. Any import files outside that scope get messed up paths.

In my code changing the Project directory given when creating PipelineManager, to the root path for the hdd fixes the problem, providing the file selected to import is on that drive.

`ImportManager = new PipelineManager(@"D:\", outputDir, intermediateDir)`

**Comment by SimonDarksideJ** [comment]
Thoughts @harry-cpp / @Jjagg , is this quickly solvable for the next point release?

**Comment by harry-cpp** [comment]
Not quickly solvable, but only a problem when using linked content.

**Comment by AliciaRaven** [comment]
I was wrong when i said changing the base directory to the drive root was working. It just seems to work because it looks for the file where it has saved it. The issue remains that it has saved it in the wrong place. In this case the associated textures are built in the output directory plus the full path taken from the source file path. Path.GetFullPath can not be trusted when using links or importing models in game as is my case.

Source and Output Paths
C:\Source Folder 1\Source Folder 2\SourceFile.dae
C:\Output Folder 1\Output Folder 2\

Becomes
C:\Output Folder 1\Output Folder 2\Source Folder 1\Source Folder 2\Texture.mgcontent

**Comment by AliciaRaven** [comment]
@harry-cpp why not easy to solve? its just a case of tracking file paths with strings and avoiding the use of Path.GetFullPath which as we have established is not reliable when input can be anywhere on a file system. Links are broken, and any in game content loading is broken. I know most game creators expect content to be built at compile time and loaded at the start of a game or level, but that leaves a huge gap in creativity. My game is held up because I have an online system where users need to upload there own content at runtime to build their own world. Creating content at compile time is fine for 2d mobile games but that has no flexibility and if an issue such as content load paths causes issues, then user created content, level editor imports and model editor applications are not going to be possible with monogame. I have invested a lot of time developing my game using MG and as most people here seem to be focused on 2d and issues like this don't get much attention I'm worried I have chosen the wrong path.

**Comment by nkomp18** [comment]
I created a new project, copied the files across and the problem was resolved. Not sure what caused it, and I no longer have the old one, sorry.

**Comment by AliciaRaven** [comment]
Just to be clear, the issues reported in this thread by nkomp18 are not related to the original issue and were just template errors. This issue is the changes to use Path.Combine that have broken imports for files outside the build directory. This includes the issue related to broken links in MGCB. Just string path management issues here, please dont push this issue down the line.

I have a hack that almost fixes this. In my game when i create an instace of PipelineManager, i have to give the projectDir path as the drive root. Then i can import files inside the game because they are then not outside that base path. This does not fix importing files that are not on the same drive as the game.

Please look into this for the next release 3.8.1 release.

**Comment by mrhelmut** [comment]
I've read your original message, a ping wasn't quite required.

Please bear in mind that MG is a community project and that we are doing what we can to move things forward. We also need to make an arbitrage in regard to what goes in or not in a release, and that sometimes include postponing an issue to avoid pushing a release back. I understand the frustration, but we have to prioritize. We are likely going to do more frequent releases from now on.

**Comment by AliciaRaven** [comment]
Ok, i understand. Thanks for responding and i also want to say i do appreciate the work you guys do.

**Comment by stromkos** [comment]
> ... why not easy to solve? 

Please note that the term "`Content` directory" refers to both the mgcb output directory and the Content root directory of the loaded game. 

The entire content build system is designed to maintain a single relative path from the `Content` source directory to the output's `Content` directory per file. 
When a texture is loaded through a model, the base asset's path becomes the relative root for that asset, stored as an `ExternalReference` object:

https://github.com/MonoGame/MonoGame/blob/1e38b48b405667f6f3958209e9424a36ddfdfe99/MonoGame.Framework.Content.Pipeline/ExternalReference.cs#L57-L63

You might suggest removing the `GetFullPath` call.  That still would not work for off drive paths. 
Worse, it would **silently break** testing and packaging games. At this point, it is better to crash and force a manual copy.

On the read side of `ExternalReference` moves the root back to `Content` appending the saved path:

https://github.com/MonoGame/MonoGame/blob/1e38b48b405667f6f3958209e9424a36ddfdfe99/MonoGame.Framework/Content/ContentReader.cs#L110

The reader is correct. All assets **must** exist under `Content`. This is by design(see above), otherwise, the packaging and subsequent loading system breaks.

---

> ... when input can be anywhere on a file system. ... users need to upload their own content at runtime

If those are your needs, you need a custom secure build system using offline parsing and validation. During that process, rewrite the texture paths to "." and co-locate the texture files in the same directory.

**Comment by damian-666** [comment]
You might loook at my sample https://github.com/damian-666/MGShadersXPlatform    i put all myh content i one mcdb file.   theres no linked refernces to maintain.  the assets are complile per platfrom and go to the right place.    took me a while to find a template that worked.. i had install netcore 3.1.. after .netocre 6.. its a good setup to target multiplafroms and i had this type of problem when i targeted only one and tried not to use shared game code.   Teh game code is using MonogameGL and the exes are thn as possible and target DX or Gl or android.  so its perfect.  u touch an fx file and everyting goes where it should

**Comment by damian-666** [comment]
But i cant load mp3 and have otehr issues so this might not fully solve ur issues.. im just doing texture s and shaders and edit he content.mgcb file manually so it doesnt add a target..   it wil use the environement  variable of the target exe
