### ISSUE TITLE
Pipeline extension 3.8 Unable to load DLL ‘FreeImage’ but works in MG Pipeline tool.

### ISSUE THREAD

**Issue by gronken** [MonoGame/MonoGame#7385]
Basically if you use FreeImage in a Pipeline extension 3.8 and use it in a project you get an error building but using the pipeline extension in the MG Pipeline tool builds fine.  

I have made a git to replicate the issue: 
https://github.com/gronken/TestFreeImage

**Here is the build log from the TestFreeImage.OpenGL Project:**
```
1>------ Build started: Project: TestFreeImage.OpenGL, Configuration: Debug Any CPU ------
1>C:/Users/_/source/repos/TestFreeImage/TestFreeImage.OpenGL/Content/file.bmp
1>C:/Users/_/source/repos/TestFreeImage/TestFreeImage.OpenGL/Content/file.bmp : error : Importer 'FreeImageEditImporter' had unexpected failure!
1>System.DllNotFoundException: Unable to load DLL 'FreeImage' or one of its dependencies: The specified module could not be found. (0x8007007E)
1>   at FreeImageAPI.FreeImage.Allocate(Int32 width, Int32 height, Int32 bpp, UInt32 red_mask, UInt32 green_mask, UInt32 blue_mask)
1>   at FreeImageAPI.FreeImage.Allocate(Int32 width, Int32 height, Int32 bpp)
1>   at FreeImagePipline.FreeImageEditImporter.Import(String filename, ContentImporterContext context) in C:\Users\_\source\repos\TestFreeImage\FreeImagePipline\FreeImageEditImporter.cs:line 14
1>   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentImporter.cs:line 45
1>   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 669
1>C:\Users\_\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\MonoGame.Content.Builder.Task.targets(138,5): error MSB3073: The command "dotnet C:\Users\_\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\\..\tools\netcoreapp3.1\any\mgcb.dll /quiet /@:"C:\Users\_\source\repos\TestFreeImage\TestFreeImage.OpenGL\Content\Content.mgcb" /platform:DesktopGL /outputDir:"C:/Users/_/source/repos/TestFreeImage/TestFreeImage.OpenGL/Content/bin/DesktopGL/Content" /intermediateDir:"C:/Users/_/source/repos/TestFreeImage/TestFreeImage.OpenGL/Content/obj/DesktopGL/Content" /workingDir:"C:/Users/_/source/repos/TestFreeImage/TestFreeImage.OpenGL/Content/"" exited with code 1.
1>Done building project "TestFreeImage.OpenGL.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ========== 

```

**Building from the MG Pipeline tool works fine:**
![image](https://user-images.githubusercontent.com/11825639/97487564-5560eb00-195d-11eb-8559-edec4930d1f7.png)

The project is explained better in problem solving topic @ monogame.net:
https://community.monogame.net/t/pipeline-extension-3-8-unable-to-load-dll-freeimage/14013

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Pipeline extension

**Comment by harry-cpp** [comment]
Since MGCB also uses freeimage, and you are referencing another freeimage version, you will cause a lot of conflict between those 2 native libs so its no wonder that stuff starts crashing right away.

If you really wanna use one of the same native libraries MonoGame.Content.Pipeline already uses, you are gonna have to either reference the native library already in the MG.C.P folder or make your pipeline extension create another process.
