### ISSUE TITLE
MGCB-Editor does not start under WSL

### ISSUE THREAD

**Issue by JordanAnthonyKing** [MonoGame/MonoGame#7492]
I do most of my development work under Ubuntu via WSL2, using an xserver for graphical applications.

Trying to launch MGCB-Editor gives the following error:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'MonoGame.Tools.Pipeline.Global' threw an exception.
 ---> GLib.GException: Icon 'emblem-symbolic-link' not present in theme Yaru
   at Gtk.IconTheme.LoadIcon(String icon_name, Int32 size, IconLookupFlags flags)
   at MonoGame.Tools.Pipeline.Global.PlatformInit() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Linux\Global.Linux.cs:line 27
   at MonoGame.Tools.Pipeline.Global..cctor() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Global.cs:line 44
   --- End of inner exception stack trace ---
   at MonoGame.Tools.Pipeline.Styles.<>c.<Load>b__9_0(ApplicationHandler h) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Linux\Styles.Linux.cs:line 55
   at Eto.Style.<>c__DisplayClass13_0`1.<Add>b__0(THandler w)
   at Eto.DefaultStyleProvider.<>c__DisplayClass9_0`1.<Add>b__0(Object widget)
   at Eto.DefaultStyleProvider.ApplyStyles(Object widget, String style)
   at Eto.DefaultStyleProvider.Eto.IStyleProvider.ApplyStyle(Object widget, String style)
   at Eto.Widget.OnStyleChanged(EventArgs e)
   at Eto.Widget.set_Style(String value)
   at MonoGame.Tools.Pipeline.Program.CommandLineInterface.Run(InvocationContext context, String project) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Program.cs:line 72
   at MonoGame.Tools.Pipeline.Utilities.CommandLineParser.<>c__DisplayClass2_1.<.ctor>b__1() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Utilities\CommandLineParser.cs:line 31
   at MonoGame.Tools.Pipeline.Utilities.CommandLineParser.Invoke(String[] args) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Utilities\CommandLineParser.cs:line 75
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Program.cs:line 22
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Ubuntu under Windows 10 via WSL2

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Install the default set of GNOME icons and you'll be fine.
