### ISSUE TITLE
Can't launch mgcb-editor

### ISSUE THREAD

**Issue by r4b8iiiiiit** [MonoGame/MonoGame#7548]
When trying to run the mgcb-editor I get the following issue:

```(mgcb-editor-gtk:199581): Gtk-WARNING **: 19:32:34.419: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(mgcb-editor-gtk:199581): GdkPixbuf-CRITICAL **: 19:32:34.854: gdk_pixbuf_calculate_rowstride: assertion 'bits_per_sample == 8' failed

(mgcb-editor-gtk:199581): GdkPixbuf-CRITICAL **: 19:32:34.859: gdk_pixbuf_calculate_rowstride: assertion 'bits_per_sample == 8' failed

(mgcb-editor-gtk:199581): Gtk-CRITICAL **: 19:32:34.907: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(mgcb-editor-gtk:199581): Gtk-CRITICAL **: 19:32:34.913: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(mgcb-editor-gtk:199581): Gtk-CRITICAL **: 19:32:34.914: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(mgcb-editor-gtk:199581): Gtk-WARNING **: 19:32:35.112: GtkHeaderBar does not have a child property called expand

(mgcb-editor-gtk:199581): Gtk-WARNING **: 19:32:35.112: GtkHeaderBar does not have a child property called fill

(mgcb-editor-gtk:199581): Gtk-WARNING **: 19:32:35.195: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)

(mgcb-editor-gtk:199581): Gtk-WARNING **: 19:32:35.198: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)

(mgcb-editor-gtk:199581): Gtk-CRITICAL **: 19:32:35.338: gtk_cairo_should_draw_window: assertion 'GDK_IS_WINDOW (window)' failed

(mgcb-editor-gtk:199581): Gdk-CRITICAL **: 19:32:35.338: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(mgcb-editor-gtk:199581): Gdk-CRITICAL **: 19:32:35.338: gdk_window_get_height: assertion 'GDK_IS_WINDOW (window)' failed

(mgcb-editor-gtk:199581): Gdk-CRITICAL **: 19:32:35.338: gdk_window_get_width: assertion 'GDK_IS_WINDOW (window)' failed```



<!-- System stats -->

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Linux (Arch/Manjaro)

#### What MonoGame platform are you using:
<!-- e.g. DesktopGL, WindowsDX, WindowsUWP, Android -->
- DesktopGL

**Comment by mrhelmut** [comment]
Please upgrade to MonoGame 3.8 and try again.

**Comment by coltonhurst** [comment]
Hello,

I am using MonoGame 3.8 and I am running into the same issue. I try to run `mgcb-editor` in Terminal, it starts to open, then crashes. I am on OS X Big Sur 11.5.2. Please let me know whatever output I should provide.

Thank you!

**Comment by PiepsC** [comment]
Same issue, same error, also in Monogame 3.8. Platform: Arch Linux x64

**Comment by jmrepetti** [comment]
I have the same problem on MacOS, I think in Manjaro I end up building it from AUR. 

Again on MacOS, I tried the Visual Studio setup path  and seems I can open .mgcb files in there (Visual Studio). 

Another question, maybe related, is there any guide on how to replace the **mgcb-editor** with the command line using **mgcb** only? 

Thanks.

**Comment by mrhelmut** [comment]
This issue has been fixed internally. However, it will only be made available for the production nugets once MonoGame 3.8.1 is released (no ETA, but working toward it).

For the time being, if you need the fix, you will have to build the nugets from source and reference them locally.

**Comment by coltonhurst** [comment]
Thanks for the update @mrhelmut !

**Comment by Apostolique** [comment]
You can also grab the teamcity builds: <https://learn-monogame.github.io/how-to/install-develop/>.

**Comment by coltonhurst** [comment]
@Apostolique great!

I tried to follow the instructions there... but when I run `mgcb-editor` in Terminal I get this error:

```
bash-3.2$ mgcb-editor
Unhandled exception. System.IO.DirectoryNotFoundException: /Users/coltonhurst/.dotnet/tools/.store/dotnet-mgcb-editor/3.8.1.2002-develop/dotnet-mgcb-editor/3.8.1.2002-develop/tools/net5.0/any/MGCB Editor.app
   at MonoGame.Content.Builder.Editor.Launcher.MacPlatform.get_LocalAppPath() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\MacPlatform.cs:line 18
   at MonoGame.Content.Builder.Editor.Launcher.MacPlatform.Run(InvocationContext context, String project) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\MacPlatform.cs:line 34
   at MonoGame.Content.Builder.Editor.Launcher.Program.<>c__DisplayClass0_1.<Main>b__1() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\Program.cs:line 36
   at MonoGame.Content.Builder.Editor.Launcher.Program.Main(String[] args) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\Program.cs:line 77
Abort trap: 6
```

**Comment by Apostolique** [comment]
Latest might still be bugged since you're getting that error.
