### ISSUE TITLE
mgcb-editor not start

### ISSUE THREAD

**Issue by kasaoli** [MonoGame/MonoGame#7613]
I installed mgcb-editor, but when writing mgcb-editor --register as the monogame documentation says, the following error message appears:

Unhandled exception: System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MonoGame.Tools.Pipeline.Program.CommandLineInterface.Launch(InvocationContext context, Boolean waitForExit) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Launcher\Program.Launcher.cs:line 67
   at MonoGame.Tools.Pipeline.Program.CommandLineInterface.Register(InvocationContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Launcher\Program.Launcher.cs:line 33
   at MonoGame.Tools.Pipeline.Utilities.CommandLineParser.<>c__DisplayClass5_0.<<CreateShortCircuitMiddleware>b__0>d.MoveNext() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor\Platform\Utilities\CommandLineParser.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Windows

**Comment by weslleyluiz** [comment]
If it helps anyone, i had the same issue with the same version in OSX.
I workaround by downgrading the version to 3.7

**Comment by Eversor** [comment]
I have the same problem on OSX 11.6.1, pressing open with MGCB-Editor from the Right click menu in solution tab doesn't do anything. Same with entering mgcb-editor in terminal. 
![Screenshot 2021-11-15 at 17 51 19](https://user-images.githubusercontent.com/733699/141821640-da565ef2-463d-4a6f-acf4-dbfff1f893e0.png)
g.

When i enter mgcb-editor --register i get :

Failed to register MGCB Editor
Unhandled exception: System.IO.IOException: The file '/Users/macmini/Applications/MGCB Editor.app/Contents/Info.plist' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at MonoGame.Tools.Pipeline.FileAssociation.CopyDirectory(String sourceDirName, String destDirName)
   at MonoGame.Tools.Pipeline.FileAssociation.CopyDirectory(String sourceDirName, String destDirName)
   at MonoGame.Tools.Pipeline.FileAssociation.InstallApplication()
   at MonoGame.Tools.Pipeline.FileAssociation.Associate()
   at MonoGame.Tools.Pipeline.Program.CommandLineInterface.Register(InvocationContext context)
   at MonoGame.Tools.Pipeline.Utilities.CommandLineParser.<>c__DisplayClass5_0.<<CreateShortCircuitMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by Eversor** [comment]
That said i'm pretty sure mgcb-editor --register is not intended to be used on MSWindows afaik, it really looks like a terminal command for linux and osx.

**Comment by GameGuess** [comment]
hello,
I have the same problem
I have the same OSX 11.6 version
since I installed VS 2022
did you find a solution?

**Comment by kasaoli** [comment]
> hello, I have the same problem I have the same OSX 11.6 version since I installed VS 2022 did you find a solution?

In my case I found that it doesn't work because my computer is 32-bit and Monogame only works on 64-bit computers

**Comment by Jesuszilla** [comment]
That's strange because I'm having MGCB problems BECAUSE Apple dropped support for 32-bit applications ages ago (64-bit only from here on out) and Wine isn't even officially supported on Big Sur or later. I mean you can install Wine through Homebrew, but it doesn't work right with 32-bit applications. I'm really curious as to whether or not it's a configuration issue on my end, or if they need to go about this another way moving forward.

**Comment by Predatorie** [comment]
I am running macOS Monterey 12.1.

I ran the dotnet commands to install and register the mgcb-editor and everything completed successfully. However, the editor is not actually associated with the file type and opens in the text editor when double clicking the content file in my project, also, using the right click open with menu in VS 2022 (preview) does nothing. I have also tested with Rider 2021.3.2 I installed the monogame plug-in and I have the same issue.

If I browse to the MGCB app and run it directly I get a damaged app message. I then used a utility to uninstall the app but now trying to re-install I get a message that it is already installed. Not sure where to go from here to be honest.

**Comment by cpt-max** [comment]
The damaged app message can also mean that the app is under quarantine. This can happen when you download an app from the internet. I don't think it should happen with a nuget install, but just in case try:
```
xattr -d com.apple.quarantine /PathTo/MGCB-Editor.app 
``` 
I also just uploaded my custom built MGCB editor, maybe that works:
https://github.com/MonoGame/MonoGame/issues/7513#issuecomment-1017085637

**Comment by Predatorie** [comment]
@cpt-max I downloaded you custom built editor, installed and it is working as expected and builds successfully, thank very much!

**Comment by mrhelmut** [comment]
Assuming it be fixed for the upcoming 3.8.1 release. Feel free to reopen if it persists on 3.8.1 once released.
