### ISSUE TITLE
Missing 'mgcb-editor-windows' dotnet tool on project build

### ISSUE THREAD

**Issue by julealgon** [MonoGame/MonoGame#7849]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

After creating a brand new DesktopGL project from the project template, I can't build the project because it fails to restore one of the editor tools registered in the project's tool manifest:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package dotnet-mgcb-editor-windows with version (= 3.8.1.263)	GameTest	C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj	1	
Error	NU1102	- Found 1 version(s) in nuget.org [ Nearest version: 3.8.1.1-develop ]	GameTest	C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj	1	
Error	NU1102	- Found 0 version(s) in Microsoft Visual Studio Offline Packages	GameTest	C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj	1	
Error	MSB3073	The command "dotnet tool restore" exited with code 1.	GameTest	C:\Users\julea\.nuget\packages\monogame.content.builder.task\3.8.1.263\build\MonoGame.Content.Builder.Task.targets	139	
``` 

Full build logs for reference:
```
1>------ Build started: Project: GameTest, Configuration: Debug Any CPU ------
1>C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj : error NU1102: Unable to find package dotnet-mgcb-editor-windows with version (= 3.8.1.263)
1>C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj : error NU1102: - Found 1 version(s) in nuget.org [ Nearest version: 3.8.1.1-develop ]
1>C:\Users\julea\AppData\Local\Temp\qdacff3f.pgw\restore.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>
1>Package "dotnet-mgcb-editor-windows" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
1>   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
1>   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
1>   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
1>
1>Tool 'dotnet-mgcb' (version '3.8.1.263') was restored. Available commands: mgcb
1>Tool 'dotnet-mgcb-editor' (version '3.8.1.263') was restored. Available commands: mgcb-editor
1>Tool 'dotnet-mgcb-editor-linux' (version '3.8.1.263') was restored. Available commands: mgcb-editor-linux
1>Tool 'dotnet-mgcb-editor-mac' (version '3.8.1.263') was restored. Available commands: mgcb-editor-mac
1>
1>Restore partially failed.
1>C:\Users\julea\.nuget\packages\monogame.content.builder.task\3.8.1.263\build\MonoGame.Content.Builder.Task.targets(139,5): error MSB3073: The command "dotnet tool restore" exited with code 1.
1>Done building project "GameTest.csproj" -- FAILED.
```

When searching for this in NuGet.org, I could also not find the specified package. The only similar one I found was this:
- https://www.nuget.org/packages/bad-echo-mgcb-editor-windows/3.8.1.2199-develop

Let me know if I'm missing something completely obvious here.

**Comment by Beyley** [comment]
https://github.com/MonoGame/MonoGame/issues/7687#issuecomment-1193317989

**Comment by julealgon** [comment]
Wouldn't it make more sense to keep this open until the issue is actually fixed @mrhelmut ?

**Comment by mrhelmut** [comment]
It has been fixed, you might want to refresh your nuget cache. https://github.com/MonoGame/MonoGame/issues/7687#issuecomment-1193620806

**Comment by xwpedram** [comment]
I fixed that. you need to install Microsoft XNA Framework and then go to Tools>Options>Nuget Package Manager and check "Allow NugGet to download missing packages" and check "Automatically check for missing packages during ..." and click on "Clear All NuGet Storage" button and OK. Now rebuild your project.
