### ISSUE TITLE
MonoGame.Framework.Content.Pipeline does not find ffmpeg/ffprobe in runtimes folder

### ISSUE THREAD

**Issue by ReMinoer** [MonoGame/MonoGame#7901]
Hi there!
I recently updated from MonoGame 3.7.1.189 to 3.81.303 and from .NET Framework to .NET 6 on my game project.
And it has gone very well, thank you for the good job ! :)

But I do have a small issue to report with **MonoGame.Framework.Content.Pipeline**. I'm using its package directly in my engine to cook my assets at runtime. (Note: because that package didn't exist in 3.7.1.189, I was using it at version 3.8.0.1375-develop until now. Not the best but it was working. ^^)

**But by updating my projects to .NET 6** for MonoGame 3.81.303, my projects depending on MonoGame.Framework.Content.Pipeline now output the runtime assemblies inside the **"runtimes/{platforms}/native"** folder structure.
**Problem is: ffmpeg and ffprobe are not next to the executable anymore and `ExternalTool.Run` is not able to find them, resulting in the following exception when cooking an audio file:**

```
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException
  HResult=0x80131500
  Message=Failed to open file saut. Ensure the file is a valid audio file and is not DRM protected.
  Source=MonoGame.Framework.Content.Pipeline
  StackTrace:
   at Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent..ctor(String audioFileName, AudioFileType audioFileType)
   at Microsoft.Xna.Framework.Content.Pipeline.WavImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(PipelineBuildEvent pipelineEvent, PipelineBuildEvent cachedEvent, String eventFilepath)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(String sourceFilepath, String outputFilepath, String importerName, String processorName, OpaqueDataDictionary processorParameters)
   at Glyph.Pipeline.RawContentLibrary.<>c__DisplayClass24_1.<CookAsset>b__0() in D:\Remi\Git\Papyrus\External\Calame\External\Glyph\Glyph.Pipeline\RawContentLibrary.cs:line 144
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
    Microsoft.Xna.Framework.Content.Pipeline.ExternalTool.Run(string, string, out string, out string, string)
    Microsoft.Xna.Framework.Content.Pipeline.Audio.DefaultAudioProfile.ProbeFormat(string, out Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioFileType, out Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioFormat, out System.TimeSpan, out int, out int)
    Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent.AudioContent(string, Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioFileType)

Inner Exception 1:
Exception: Couldn't locate external tool 'ffprobe'.
```

The workaround is pretty simple: you can set your PATH with a folder containing ffmpeg & ffprobe and it will work. But it's kinda sad that it doesn't find them by default since there are provided by the package.

Note that it doesn't seems to be an issue for packed/published executables (like mgcb CLI) since the package runtimes will be output next to the executable in that case.

Any insight on the subject ?
Would it be possible to make `ExternalTool.Run` look for executables in the valid target platforms "runtimes" folders (if existing) ?
(It is already looking for ["linux" and "osx" folders](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/ExternalTool.cs#L129) to resolve ffmpeg & ffprobe.)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows / Linux

#### What MonoGame platform are you using:

- WindowsDX / DesktopGL

**Comment by ReMinoer** [comment]
I ended being able to use MonoGame.Framework.Content.Pipeline package without computer setup with a bit of configuration on my projects:

1. As implied by [MonoGame.Content.Builder.Editor](https://github.com/MonoGame/MonoGame/tree/develop/Tools/MonoGame.Content.Builder.Editor) csproj files, it seems mandatory to provide a **`<RuntimeIdentifier>`** in your executables csproj files depending on MonoGame.Framework.Content.Pipeline (directly or indirectly), among the ones supported by the package (win-x64, linux-x64 & osx), to output correctly the runtime dependencies:

    ```csproj
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
      </PropertyGroup>
      ...
    </Project>
    ```

    This allow your project to directly output platform-specific binaries at build and so to copy the corresponding package runtime DLLs next to the executable, including ffmpeg/ffprobe.

    That say, you will not have that behaviour if you provide multiple RuntimeIdentifiers, at least not in Visual Studio, since it will require to specify the wanted runtime identifier in the build command line. So in a Visual Studio environment, the best seems to have **one project by platform** if you are using MonoGame.Framework.Content.Pipeline, so each of them can have **a unique RuntimeIdentifier**.

    Being forced to have platform-specific executable projects when using using MonoGame.Framework.Content.Pipeline seems acceptable but the RuntimeIdentifier property remains kinda obscure and nothing except the csproj files of [MonoGame.Content.Builder.Editor](https://github.com/MonoGame/MonoGame/tree/develop/Tools/MonoGame.Content.Builder.Editor) hint to it.

   As I said in my initial post, maybe some code to **resolve the runtime assemblies from inside the output runtimes/ folder would be ideal** to make the MonoGame.Framework.Content.Pipeline package work without indicate a RuntimeIdentifier in executable csproj files.

2. I also encountered issues with **mgfxc** dependencies. MonoGame.Framework.Content.Pipeline package is including those dependencies as **content** & **contentFiles** but the problem is that they are not configured to be copied to dependent projects output.

   To do that, the property **PackageCopyToOutput** might be lacking on the Content item [at line 277 of MonoGame.Framework.Content.Pipeline.csproj](https://github.com/MonoGame/MonoGame/blob/ea32c6cbae80614e8115b2bbfbbb73ec7e9d6a2d/MonoGame.Framework.Content.Pipeline/MonoGame.Framework.Content.Pipeline.csproj#L227):

    ```csproj
    <ItemGroup>
      <Content Include="..\Artifacts\MonoGame.Effect.Compiler\$(Configuration)\*" Exclude="..\Artifacts\MonoGame.Effect.Compiler\$(Configuration)\*.nupkg" Visible="false">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <PackageCopyToOutput>true</PackageCopyToOutput>
      </Content>
    </ItemGroup>
    ```

    As a workaround, I ended having to include those files as content of my own directly dependent project, using `GeneratePathProperty="true"` and `$(PkgMonoGame_Framework_Content_Pipeline)` to find them:

    ```csproj
    <Project Sdk="Microsoft.NET.Sdk">
      <ItemGroup>
        <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.1.303" GeneratePathProperty="true" />
        ....
      </ItemGroup>
      <ItemGroup>
        <Content Include="$(PkgMonoGame_Framework_Content_Pipeline)\content\*">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
      </ItemGroup>
      ...
    </Project>
    ```

For the moment, I'm good with my workaround since everything is done in my .csproj files.
**That say, do you have any feedback about those two issues and the suggested solutions ?**

Thanks.

**Comment by damian-666** [comment]
**Thanks.**.!!!!!    the feedback i have now is that is seems to be right **on point.**   when i recover from a similar issue and fail to even revert to last time it worked,  

 This DOES seem like you are getting to the root of the issue(s)    I will definitely try but I don't even use mp3 and am having very similar issues.   But it's more than just mp3.. its all shared content and multitargeting, with a shared net6 core  that is getting harder to maintain.


 I willl TRY it  on my   https://github.com/damian-666/MGShadersXPlatform ( which is now broken even for me after a night of hacking, but i reverted changes.. )   and report... the rest below is TLDR. i had quite a miserable nigth, now reinstalling vs 2022 non preview and trying that...   im at the point where i have to reinstall  and clean everything.


i think specific  issues that might be fixable in content builder might be 
 **1.    <BaseOutputPath>..\..\bin</BaseOutputPath> isn't added... to the path the content builder uses..**   Since it was repeated i put it there.  I don't know if its a good idea tho, because of these issues it might be due to this.

  vs 2022 issue?    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>  doesnt seem to work have an effect either..  ??  still investigating..   i rather leave it out as  the default is true.
I willl TRY it and report... the rest below is TLDR. i had quite a miserable nigth, now reinstalling vs 2022 non preview and trying that...   im at the point where i have to reinstall  and clean everything.

I had my solutions working with a core net6 lib ( was netstandard20 but thats clearly left for dead) ,   for wpf netcore, level editor, a windows dx, a console GL, and an android GL each with a separate proj file as you suggested.

the content build should only be in the exe launcher.. it has a link to the content  file by add existing as LINK.. BUT minie it uses a shared bin folder requiring a path like ..\bin so that build products aren't copies all over the place..  (I'm not sure if theis is a great idea, its an optimization and mabye its causes issues).   the content builder should ONLY in the targets, one per project, target as you suggested... with a link to the the content.mgcb file.       the core module has the content there deeper in the tree.. it needs get copied back up the tree and deal with the added target folders.   The core  is linked to  only MG lib as 3.81. latest hotfix, w GL but as a proxy , its not making GL get used jsut to get the MG stuff to build.   the contents sources reside ,  there build its should not be build there.. However, the dependency stuff  in vs studio, might need it to be marked as something other than None. ... so you can touch an fx file , build and see the result.

BUT then, I had ti working for me at least, but i went to to make it simpler, use ANY CPU , just debug and release,  I remove these explicit paths and targets , ( which cause permutations and explosive configurations in sln  and proj files) but, mabye   brings up the package ID thing you found out about..   i remove analysis and deployment on dlls since the whole thing is supposed to be packaged higher up.  now its all broken..


So , as a WARNING..  to all USERS.. if you encounter this stuff.. both MGcontent and VS studio has serious flakiness.  ( and now, so do I)   I recommend manually building ( even wiht the visual UI content builder ) , copy your content to the exe and keep working on your own problems that aren't related to shaders and graphics mabye,  till this stabilizes..


MIght  have more like using the other scripting build stuff, command line or  the continuous integration use, but i'm ok with Vs2022 ive a tiny team.

my ideal config would use AnyCPU wherever it can.. BUT 
I dont know if ANYCpu is a good choice.   i might just have any CPU.. ARM64, and   x64, but there are arguments that 32 bit simd code is faster and its still supported.

but as you mentioned.. removing targets causes some packaging ID or related issue.     (  so it broke when i used ANYCPU, BaseOutput Path and remove some stuff i though wasnt needed.. like packaging on the dlls.   


ADVICE, if you are close to release and using netcore 6 alread the old way,  stay wiht mg 3.8 and DONT UPGRADE !    most companies use 2 year old tools by the time they ship.   I had netcore 6 working iwht MG 3.8, and the old 3.1 content.. ,  fine enough..  should have stayed there  fro months, but . Now I'm in too deep, determined to get through ...ill have to sooner or later.


Or if this above doesnt work, manually copy the content targets and just wait till its fix or script it.

ON a general note pretty much everyone is struggling with all this x platform stuff, across the board. NOW, i just want a working dev setup, while this gets sorted out.  there are issues that may need changes , working basic samples, MG templates AND vs2022 tooling..   i just need to target WPF...netcore windows dx and GL,  and android to get back to my own work.. im 3 weeks behind because of all the reconstruction..  if  i had a major company, close to shipping id be using 2 year old tool chain because this- always- happens even, targeting on one platfrom.   but I'm not near release and want to embrace the new stuff so i know where to optimize or not.. i know its needed to be done, all these major updates,  but i think its early to expect perfect operations, and IMO way to early to deploy and ship anything AOT, or any way at all.. .. not even close.   i haven't bundled to AAB or build AOT or deploy anything properly  sent  a new bundle to to Google play beta  and i dont expect to for MONTHS.   but i do need to get back to my development.

  i think the core devs are resting as they should, but flux on Open sources from Microsoft and Jetbrains and indies, other hubs is daily ,  but i want to stay with mg 3.8.1 even if a few hacks needed for now.

**Comment by damian-666** [comment]
UPDATE: so https://github.com/damian-666/MGShadersXPlatform  is updated , i hope someone else can build it and run it, at on vs2022, and i think fully works and copies stuff correctly..  i hope.

  this is  a bit #offtopic, as far as your problems with  ffmpeg , but its relevant as you can have trouble with even basic multitarget copies of compiled assets going to where they need to go and setting up solutions.  I agree one project per platform, one shared net6 core with Game class and some other net6 libs with shared code is best.   now i have no issues that need fixes or special properties, I just got my tools and or files in a bad state ... In my case , to get sane results i needed to clean all local caches , user files and temp files recently placed by dev studio, clear any nuget stuff..   and fix my relative paths.    still, deploying to Android might launch the emulator and THEN to the phone.. its just flaky, takes lots of time and careful checking.  But its workable now.   


 In my case , needed to clean all local caches , user files , nugets, and temp files recently placed by dev studio, clear any nuget stuff..   and fix my relative paths to ..\bin.    stiil deploying to Android might launch the emulator and  but THEN later to the phone.. vs 2022 preview is good, its just flaky, takes lots of time and careful checking.

so **corrections** : ANY cpu does work fine for me now.. The system figures it out.  and on android, even deploying AOT, i think.
. i did add and add  an ARM64 config, I'm not sure its necessary.    it does complicate the sln .

**There is not a problem with  BaseOutputPath  to ..\bin,  as i suspected in my earlier comment.**.

my BaseOutputPath is ..\bin and my Package output path is $(OutputPath) .  so its ok now, no repeat folder symbols, no excessive copying except in obj maybe.. its good enough.


On the first build,  wth this solution in VS 2022..
First is if you get a warning  about " Fast Up-to-date Check", what's happening is that it might detect that its not syncing, or that its building too often.     in my case i can ignore it.    the second build is fast and if i touch an asset it does build and place it.  I did nothing special but in some cases one may have to , if builds are slow every time and you didnt change any core assets..


something like this can fix this issue:  
		  <UpToDateCheckInput Include="Source Codes\MGCore\Content\Content.mgcb"/>
		  <UpToDateCheckInput Include="Source Codes\MGCore\Content\ClipShader.fx"/>
		  <UpToDateCheckOutput Include="MGCore.dll" />
	  </ItemGroup>

got this from here..
 https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md


#aslo offtopic, sore
I tried to hide the console window in DX but that works only when launched from debugger.. its probably not hard to make another exe to launch your console window hidden or find another way.

tested desktop GL on windows, desktop DX, texture change, touch and shader touch, build/ copy on all those see the new xnb, and result, on Android emulator v 23 and arm 64 samsung via usb, release and debug with thsi setup.. its not quite a basic shared asset game core template but close.   if you want to target just phones, tablets and pcs.. at least, thats a billion devices  or so

**Comment by mrhelmut** [comment]
Please refer to #8124 while this issue is being worked on.

**Comment by SimonDarksideJ** [comment]
This has since been resolved in `3.8.4` and the same improvements have been included in the new Content Builder approach.

If anyone is still having issues, please reopen this log
