### ISSUE TITLE
MGCB-Editor Crashes Immediately

### ISSUE THREAD

**Issue by acheddadi** [MonoGame/MonoGame#7909]
mgcb-editor immediately crashes when first launched in a new mgdesktopgl project and throws the following error:

`Unhandled exception. System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/acheddadi/.nuget/packages/dotnet-mgcb-editor-linux/3.8.1.303/tools/net6.0/any/mgcb-editor-linux-data/mgcb-editor-linux' with working directory '/home/acheddadi/Documents/CSharpGame'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at MonoGame.Content.Builder.Editor.Launcher.Program.Main(String[] args) in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor.Launcher/Program.cs:line 27`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Linux Manjaro Arm64

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
arm64 as an host is not supported.
