### ISSUE TITLE
[Error] Can't load model from content

### ISSUE THREAD

**Issue by cmdRus** [MonoGame/MonoGame#7977]
### 1. I was created a project from a template
![Screenshot 2023-01-09 192609](https://user-images.githubusercontent.com/47587721/211344258-e6a46bc5-642f-4d9f-a07c-a1028bbe2f01.jpg)
### 2. I added 3d model's to `Content.mgcb`
![Screenshot 2023-01-09 192747](https://user-images.githubusercontent.com/47587721/211345381-95850028-98d0-4433-b9cc-2d9328e6c5f1.jpg)
### 3. In the object `Content` no one was loaded
![Screenshot 2023-01-09 192734](https://user-images.githubusercontent.com/47587721/211345388-56e22060-3fa4-4efd-9665-00d87702f95e.jpg)
### 4. And an error comes out:
```c#
Microsoft.Xna.Framework.Content.ContentLoadException
  HResult=0x80131500
  Message=Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]] (Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline]])
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(ContentReader reader)
   at Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at Test3DDemo2.LoadContent() in C:\Users\boris\OneDrive\Документы\Projects\Project1\Project3\Class1.cs:line 49
   at Test3DDemo2.Initialize() in C:\Users\boris\OneDrive\Документы\Projects\Project1\Project3\Class1.cs:line 42
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>$(String[] args) in C:\Users\boris\OneDrive\Документы\Projects\Project1\Project3\Program.cs:line 3
```
### 5. In `bin` folder there are
![Screenshot 2023-01-09 192825](https://user-images.githubusercontent.com/47587721/211346009-3201b78b-94ee-4a1f-9181-892c2426e1e9.jpg)

**Comment by MrScautHD** [comment]
You model type is not supported use fbx or obj

**Comment by MrScautHD** [comment]
And close this issue pls.

**Comment by cmdRus** [comment]
The problem was solved. THX 😄
