### ISSUE TITLE
MGCB editor crashes

### ISSUE THREAD

**Issue by SakeyJakey** [MonoGame/MonoGame#7979]
Whenever I try to open an mgcb file i get this error:

System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at MonoGame.Tools.Pipeline.Styles.<>c.<Load>b__0_0(MenuBarHandler h)
   at Eto.Style.<>c__DisplayClass13_0`1.<Add>b__0(THandler w)
   at Eto.DefaultStyleProvider.<>c__DisplayClass9_0`1.<Add>b__0(Object widget)
   at Eto.DefaultStyleProvider.ApplyStyles(Object widget, String style)
   at Eto.DefaultStyleProvider.Eto.IStyleProvider.ApplyStyle(Object widget, String style)
   at Eto.Widget.OnStyleChanged(EventArgs e)
   at Eto.Widget.set_Style(String value)
   at MonoGame.Tools.Pipeline.MainWindow.PipelineMenuBar..ctor() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.eto.cs:line 24
   at MonoGame.Tools.Pipeline.MainWindow.InitalizeMenu() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.eto.cs:line 287
   at MonoGame.Tools.Pipeline.MainWindow.InitializeComponent() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.eto.cs:line 60
   at MonoGame.Tools.Pipeline.MainWindow..ctor() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.cs:line 46
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Program.cs:line 50

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Cross platform desktop OpenGL

**Comment by Apostolique** [comment]
Last time I saw this error, I had to update to a newer version of .NET 6. <https://dotnet.microsoft.com/en-us/download>

You can know with
```
dotnet --version
```
and 
```
dotnet --list-sdks
```
Right now I'm on `6.0.405` on both.

**Comment by SakeyJakey** [comment]
> Last time I saw this error, I had to update to a newer version of .NET 6. <https://dotnet.microsoft.com/en-us/download>
> 
> 
> 
> You can know with
> 
> ```
> 
> dotnet --version
> 
> ```
> 
> and 
> 
> ```
> 
> dotnet --list-sdks
> 
> ```
> 
> Right now I'm on `6.0.405` on both.

Thank you, this worked
