### ISSUE TITLE
Pipeline tool crashes every time with the MGCB editor

### ISSUE THREAD

**Issue by BrendanDs** [MonoGame/MonoGame#8012]
running the latest version of monogame on my visual studio 2022 and my pipeline tool always crashes and shoots out the message below. maybe i've been searching in the wrong places but cant find an answer to my problem so far. thanks for taking the time to view into this. 

System.OverflowException: The image data generated an overflow during processing.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.Initialize(BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder..ctor(SafeMILHandle decoderHandle, BitmapDecoder decoder, Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, Boolean insertInDecoderCache, Boolean isOriginalWritable, Stream uriStream, UnmanagedMemoryStream unmanagedMemoryStream, SafeFileHandle safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapDecoder.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapFrame.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at Eto.Wpf.Drawing.BitmapHandler.Create(Stream stream)
   at Eto.Drawing.Bitmap..ctor(Stream stream)
   at Eto.Wpf.Drawing.IconFrameHandler.Create(IconFrame frame, Func`1 load)
   at Eto.Drawing.IconFrame..ctor(Single scale, Func`1 load)
   at Eto.Drawing.IconFrame.FromResource(Single scale, String resourceName, Assembly assembly)
   at Eto.Drawing.Icon.GetResources(String resourceName, Assembly assembly, List`1 frames)
   at Eto.Drawing.Icon.FromResource(String resourceName, Assembly assembly)
   at MonoGame.Tools.Pipeline.MainWindow.InitializeComponent() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.eto.cs:line 52
   at MonoGame.Tools.Pipeline.MainWindow..ctor() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\MainWindow.cs:line 46
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Program.cs:line 50

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cmfrydos** [comment]
Did you check your color profile as is suggested here? https://stackoverflow.com/questions/63510630/wpf-bitmapimage-exception-the-image-data-generated-an-overflow-during-processin

**Comment by stromkos** [comment]
What size is the image?
