### ISSUE TITLE
unable to run mgcb-editor in Debian

### ISSUE THREAD

**Issue by Kaifungamedev** [MonoGame/MonoGame#8041]
I'm trying to run the mgcb-editor in Debian, but I keep getting this error:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.InitCheck(String progname, String[]& args)
   at Eto.GtkSharp.Helper.Init()
   at Eto.GtkSharp.Forms.ApplicationHandler.Initialize()
   at Eto.WidgetHandler`1.Eto.Widget.IHandler.Initialize()
   at Eto.Widget.Initialize()
   at Eto.Widget..ctor()
   at Eto.Forms.Application..ctor(InitHelper init)
   at Eto.Forms.Application..ctor(Platform platform)
   at Eto.Forms.Application..ctor(String platformType)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/Program.cs:line 27
```
Does anyone know how to fix this?
#### What i have tried
* Reinstalling the templates
* following this [guide](https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_ubuntu.html)
* Compiling from source
* uninstalling and reinstalling dotnet
> **Note**:
> i have also asked this question [here](https://community.monogame.net/t/unable-to-run-mgcb-editor-in-debian/19091) but with no response as of posting this.
#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Debian

#### What MonoGame platform are you using:
- DesktopGL

**Comment by AristurtleDev** [comment]
Hi @Kaifungamedev 
This looks like it's trying to find the GTK3 stuff on your system but is unable to locate it.

Can you try ensuring you have it installed

```
sudo apt install libgtk-3-0
```

Then see if that resolves the issue?

**Comment by Kaifungamedev** [comment]
hmmm now i get this error:
System.ArgumentOutOfRangeException: Font Family specified is not supported by this system (Parameter 'familyName')
Actual value was Cantarell.
   at Eto.GtkSharp.Drawing.FontFamilyHandler.Create(String familyName)
   at Eto.Drawing.FontFamily..ctor(String familyName)
   at Eto.GtkSharp.Drawing.FontHandler.get_Family()
   at Eto.Drawing.Font.get_Family()
   at MonoGame.Tools.Pipeline.Pad.InitializeComponent() in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/Controls/Pad.eto.cs:line 36
   at MonoGame.Tools.Pipeline.Pad..ctor() in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/Controls/Pad.cs:line 23
   at MonoGame.Tools.Pipeline.ProjectControl..ctor() in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/Controls/ProjectControl.eto.cs:line 21
   at MonoGame.Tools.Pipeline.MainWindow.InitializeComponent() in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/MainWindow.eto.cs:line 74
   at MonoGame.Tools.Pipeline.MainWindow..ctor() in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/MainWindow.cs:line 46
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in /home/runner/work/MonoGame/MonoGame/Tools/MonoGame.Content.Builder.Editor/Program.cs:line 50

**Comment by AristurtleDev** [comment]
This error looks like it's coming from the ETO framework side, which is the library the MGCB Editor uses to create the GUI for the editor. I'm not familiar with it enough to help any further

Looking around, it seems this was a similar issue on Mac as well in this Issue that was closed https://github.com/MonoGame/MonoGame/issues/7513#issuecomment-974274714

All I could find was that 3.8.1 was supposed to ship the fix for it, but that might have been just mac specific
cc: @harry-cpp

**Comment by stromkos** [comment]
install the fonts-cantarell  package.

**Comment by TheK0tYaRa** [comment]
How come this still isn't a caught exception with clearer instructions?
