### ISSUE TITLE
EnableDefaultLighting() causes an exception when used on a DX platform

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#8495]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.2.1105

### Which MonoGame platform are you using?

MonoGame Windows Desktop Application (mgwindowsdx)

### Operating System

Windows

### Description

When enabling the default Effect.EnableDefaultLighting() in a WindowsDX build, it causes an exception.

The same code on a GL platform does not.

### Steps to Reproduce

Load a Model and then attempt to draw it with the following example method:

```csharp
    void DrawModel(Model aModel, Matrix aWorld, Matrix aView)
    {
        //Copy any parent transforms
        Matrix[] transforms = new Matrix[aModel.Bones.Count];
        aModel.CopyAbsoluteBoneTransformsTo(transforms);

        //Draw the model, a model can have multiple meshes, so loop
        foreach (ModelMesh mesh in aModel.Meshes)
        {
            //This is where the mesh orientation is set, as well as our camera and projection
            foreach (BasicEffect effect in mesh.Effects)
            {
                effect.EnableDefaultLighting();
                effect.PreferPerPixelLighting = true;
                effect.World = transforms[mesh.ParentBone.Index] * aWorld;
                effect.View = aView;
                effect.Projection = currentProjection;
            }

            //Draw the mesh, will use the effects set above.
            mesh.Draw();
        }
    }
```

This runs fine on OpenGL, however, causes an exception in the "Draw()" call on Windows DX

### Expected Behavior

The EnableDefaultLighting() call should enable default lighting on all platforms and be able to render.

### Resulting Behavior

```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in MonoGame.Framework.dll: 'An error occurred while preparing to draw. This is probably because the current vertex declaration does not include all the elements required by the current vertex shader. The current vertex declaration includes these elements: SV_Position0, TEXCOORD0.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 SharpDX.SharpDXException : HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
   at SharpDX.Direct3D11.Device.CreateInputLayout(InputElement[] inputElementDescsRef, Int32 numElements, IntPtr shaderBytecodeWithInputSignatureRef, PointerSize bytecodeLength, InputLayout inputLayoutOut)
   at SharpDX.Direct3D11.InputLayout..ctor(Device device, Byte[] shaderBytecode, InputElement[] elements)
   at Microsoft.Xna.Framework.Graphics.InputLayoutCache.GetOrCreate(VertexBufferBindings vertexBuffers)
```

**Comment by tomspilman** [comment]
@SimonDarksideJ what effect were you using at the time?

**Comment by SimonDarksideJ** [comment]
Basic Effect, just the default

**Comment by squarebananas** [comment]
## Summary of the related discord discussions

- EnableDefaultLighting will cause BasicEffect to use the following technique and VS Input:

```
BasicEffect_PixelLighting_Texture_NoFog

struct VSInputNmTx
{
    float4 Position : POSITION;
    float3 Normal   : NORMAL;
    float2 TexCoord : TEXCOORD;
};
```
- The model file this issue relates to contains no normal data (Ground.x within https://github.com/SimonDarksideJ/XNAGameStudio/tree/master/Samples/ChaseCamera_4_0/ChaseCameraContent) and has the following VertexDeclaration:

```
{Offset:0 Format:Vector3 Usage:Position UsageIndex: 0}
{Offset:12 Format:Vector2 Usage:TextureCoordinate UsageIndex: 0}
```
- XNA will automatically add normals to the XNB file if none exist in the source file.

- Currently the MGCB editor does not do this by default. However with the GenerateTangents option set to true, both normals & tangents will be generated.

- A simple fix would be to change the default to true. There are lots of usages which do not need all this extra normal/tangent data though (for example sky domes).

- Another fix would be to uncomment the `PostProcessSteps.GenerateNormals` line for the Assimp importer. I have not tested how that compares to MeshHelper.CalculateNormals so it could output different results.
https://github.com/MonoGame/MonoGame/blob/aff977c769c2a447dc9f699df93a578acfa7975a/MonoGame.Framework.Content.Pipeline/OpenAssetImporter.cs#L306

- In additional to all of this, without any normal data other graphical glitches may occur for DesktopGL. These glitches seem to change depending on the graphics hardware in use. For me integrated Intel fails while Nvidia succeeds (my guess is Nvidia might apply fixes for mismatched shader inputs usage / offsets alignments).

## Suggestions

- Split the GenerateTangents (with normals) MGCB option into separate GenerateNormals (default true) and GenerateTangents (default false) options.

- Check VertexDeclaration is valid for the Technique and throw a descriptive exception or debug warning.

- Any changes should also be tested for other files with different formats & export options (differing VertexElement arrangements). Ideally more Unit Tests could be added alongside this testing.

**Comment by tomspilman** [comment]
> Check VertexDeclaration is valid for the Technique and throw a descriptive exception or debug warning.

That is the first order of business.  It should give them feedback allowing them to fix their model data.

This is particularly important because they could be using a custom model format with custom vertex data.  It may not be data processed with the content pipeline.

So a good descriptive error message is the best fix here.

> Split the GenerateTangents (with normals) MGCB option into separate GenerateNormals (default true) and GenerateTangents (default false) options.

As long as it doesn't break anyone importing XNA content over that should be fine.

I assume `GenerateNormals` means "generate normals if the model doesn't already have normals"  (same as GenerateTangents i think).

Note `GenerateTangents` implies it is also generating normals, so maybe a enum selection is better here?  Just don't want to break working MGCB files that assume that `bool GenerateTangents` exists break.  So care would need to be taken to support old content projects if we did this.

**Comment by tomspilman** [comment]
Note we have a notification on DirectX 11 when the vertex shader and the vertex buffers did not match up:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Graphics/Vertices/InputLayoutCache.cs#L172

Not sure why this isn't throwing in this case.

**Comment by squarebananas** [comment]
> Not sure why this isn't throwing in this case.

I did post the exception message and stack trace in the discord thread as you requested last week. I should have mentioned that here.

`System.InvalidOperationException: 'An error occurred while preparing to draw. This is probably because the current vertex declaration does not include all the elements required by the current vertex shader. The current vertex declaration includes these elements: SV_Position0, TEXCOORD0.'`

Yeah it does throw there, but it only contains information about what elements you gave it not what was required.

What I was suggesting is a check that the "VertexDeclaration is valid for the Technique" and an error message if not. The idea I had (the feasibility would need investigating) was to compare the layouts and include the missing `VertexElement` in the message.

`BasicEffect` has 32 possible techniques and the technique used is automatically selected internally depending on `BasicEffect` properties that are set. This approach is also used by the other built-in effects (`AlphaTestEffect`, `DualTextureEffect`, `EnvironmentEffect` and `SkinnedEffect`).

Without the MonoGame source, I'm not entirely sure it is possible to see the required vertex layout for each technique currently. As far as I can tell the code summary tags, website documentation and API reference do not contain this information either.

In addition the error message only appears on a crash (at least with WindowsDX). With Simon's original DesktopGL issue where the ground texture was not rendering correctly, he wouldn't have any warning message in the output window as there was no crash. A message about the missing vertex element may have helped identify the missing normal data within the model.

> As long as it doesn't break anyone importing XNA content over that should be fine.

Currently the XNB files built with XNA work in MonoGame, it's the ones built by MGCB that don't. Generating normals by default (if the model doesn't contain them) should improve importing XNA models.

I agree though this needs thorough testing. In the third suggestion I mentioned adding more Unit Tests with more files. In a different discord discussion I wrote a bit more about this, so I'll paste that here:

> "Also it might be worth adding a wider range of assets to the MonoGame tests as well, even ones that don't work but should (output warnings only for now). If all the XNA sample model files were collated and added it would possibly highlight more issues that need fixing."

**Comment by squarebananas** [comment]
Looks great! Just knowing what is required by the vertex shader is much more informative. Especially for the built-in effect resources.

Just to summarise the findings from last week:

```
Platform     Graphics    Crash	     Texture
DesktopGL    Intel       No Crash    Incorrect
DesktopGL    Nvidia      No Crash    Correct
WindowsDX    Intel       Crash       -
WindowsDX    Nvidia      Crash       -
```

It seems the effect of a missing VertexElement can differ quite a bit. From what I can tell this new GenerateInputElements code will throw even if it is handled. I was going to suggest a debug warning when it works anyway, but maybe throwing regardless is better. That way someone developing with hardware that doesn't crash is force to fix VertexElement crash cases even if they don't see the issue themselves.

Thanks again.

**Comment by bjornenalfa** [comment]
> Right. I fixed that in the new native backend. It provides a message showing what the shader requires:
> 
> ![image](https://private-user-images.githubusercontent.com/103522/370721162-e4924c1f-9d2b-4209-bf72-c74dfe64a9a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzczNzIsIm5iZiI6MTcyNzI3NzA3MiwicGF0aCI6Ii8xMDM1MjIvMzcwNzIxMTYyLWU0OTI0YzFmLTlkMmItNDIwOS1iZjcyLWM3NGRmZTY0YTlhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNTExMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTMwZjBmNmM1MTIzNzAxMzE1ZmFkMGQyYjFlNjJhNTI0NWM0MTU4M2VkNjVjMGJiNWM2MDhiZDhlNjk4MWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PmO29En-Toh7-OWLp8irOi3gN_Qd25raB9QoH6U8E4I)

I think it would be useful to show what elements are in the current vertex definition too, or at least which ones are missing.
