### ISSUE TITLE
Intermittent segfault in Game constructor

### ISSUE THREAD

**Issue by e8newallm** [MonoGame/MonoGame#8572]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.2.1105

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Linux

### Description

When declaring an array of objects that are references to a single static object, and do so with an inline field initialisation inside a class inheriting Game, there is an intermittent segfault happening.

If the field is declared, but defined inside the inheriting class' constructor, or if the class stops inheriting Game, the issue goes away

I have reproduced this on two different Linux machines, and someone on Discord was able to reproduce it on Windows.

I'm speculating that Game doesn't expect there to be any dynamic memory allocated before the constructor runs, and since inline initialisation is technically before the object constructor triggers, it fails. 

### Steps to Reproduce

Pull the example repo and run runrepeat.sh

### Minimal Example Repo

https://github.com/e8newallm/MonoGameBug

### Expected Behavior

The bare bones application should open and close with no issues repeatedly

### Resulting Behavior

A segfault and the application crashing occurs intermittently. 

./run.sh: line 1: 58028 Segmentation fault      (core dumped) bin/Release/net8.0/GameMono

gdb backtrace:

> __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:461
> 461             VMOVU   -VEC_SIZE(%rsi, %rdx), %VMM(5)
> (gdb) bt
> #0  __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:461
> #1  0x00007fff740b5b17 in SDL_memcpy_REAL (dst=<optimized out>, src=<optimized out>, len=523680) at /usr/src/debug/sdl2/SDL2-2.30.9/src/stdlib/SDL_stdlib.c:527
> #2  mem_read (context=0x555555753180, ptr=<optimized out>, size=523680, maxnum=<optimized out>) at /usr/src/debug/sdl2/SDL2-2.30.9/src/file/SDL_rwops.c:493
> #3  0x00007fff740bf5cf in SDL_RWread_REAL (context=0x555555753180, ptr=0x7fff6fd4b010, size=523680, maxnum=1) at /usr/src/debug/sdl2/SDL2-2.30.9/src/file/SDL_rwops.c:826
> #4  SDL_GameControllerAddMappingsFromRW_REAL (rw=0x555555753180, freerw=1) at /usr/src/debug/sdl2/SDL2-2.30.9/src/joystick/SDL_gamecontroller.c:1521
> #5  0x00007fff78f156f9 in ?? ()
> #6  0x0000000000ea716f in ?? ()
> #7  0x00007ffff786f878 in vtable for InlinedCallFrame () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.10/libcoreclr.so
> #8  0xffffffffffffffff in ?? ()
> #9  0x0000000000000000 in ?? ()

**Comment by stromkos** [comment]
What happens if there is a short sleep in the loop script?

**Comment by e8newallm** [comment]
The issue still persists with a sleep in the loop. I don't believe the issue is related to the pace at which you run the software over and over, as I originally got the issue running my project normally, and at first the issue was consistently happening every time I ran my code.

**Comment by mrhelmut** [comment]
> I'm speculating that Game doesn't expect there to be any dynamic memory allocated before the constructor runs, and since inline initialisation is technically before the object constructor triggers, it fails.

```Game``` expect nothing, and if we look at this purely from what you describe, it would make it look like a .NET bug with static initializer more than a bug with MonoGame.

The stacktrace is weird, though. That segfault happens in ```SDL_GameControllerAddMappingsFromRW()```, which either means that there is a bug within SDL2, or that the C# wrapper has a wrongly marshalled function signature for that function (in that case I would suspect that we updated SDL2 without checking if some functions had changed). Static initializers likely make this to trigger because of some memory alloc overlap, but is likely not the cause itself.

**Comment by ThomasFOG** [comment]
Considering this fixed as ```SDL_GameControllerAddMappingsFromRW()``` is no more used.
